#!/usr/bin/env python3
"""M5 step 2: write cube_table.jsonl as Lean data (lean-sb/RootedM5/Data/D_XX.lean, Checks/K_XX.lean,
Table.lean). Deterministic: the 781 cases in sorted tag order, cut into fixed chunks of CASES_PER_CHUNK
cases (so a later merge of M6 rows only changes the chunks that contain them), entries in the order of
the family's listed words (widx). Long lists are cut into defs of at most CH elements.
usage: m5_gen_lean.py"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
LEAN = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..', 'lean', 'sbsound', 'RootedM5'))
CASES_PER_CHUNK = 80
CH = 200          # entries per def
CHL = 300         # leaves per def
PART_WEIGHT = int(os.environ.get('M5_PART_WEIGHT', 1500))   # entries + leaves per check module
OPT = {'O1': '.o1', 'O2': '.o2', 'O3': '.o3'}


def lst(xs):
    return '[' + ', '.join(xs) + ']'


def main():
    rows = [json.loads(l) for l in open(os.path.join(HERE, 'cube_table.jsonl'))]
    keys = json.load(open(os.path.join(HERE, 'cases.json')))
    cases = {t: [] for t in keys}
    for r in rows:
        cases.setdefault(r['tag'], []).append(r)
    tags = sorted(cases)
    assert len(tags) == 781
    os.makedirs(os.path.join(LEAN, 'Data'), exist_ok=True)
    os.makedirs(os.path.join(LEAN, 'Checks'), exist_ok=True)
    nchunks = (len(tags) + CASES_PER_CHUNK - 1) // CASES_PER_CHUNK
    for ci in range(nchunks):
        ctags = tags[ci * CASES_PER_CHUNK:(ci + 1) * CASES_PER_CHUNK]
        L = [f'/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py from cube_table.jsonl. Do not edit.',
             f'   Cases {ci * CASES_PER_CHUNK}..{ci * CASES_PER_CHUNK + len(ctags) - 1} of the 781 (sorted list tags). -/',
             'import RootedM5.Basic', '', 'namespace SB.Rooted.M5.Data', 'open SB.Rooted.M5', '']
        names = []; weight = {}
        for j, tag in enumerate(ctags):
            idx = ci * CASES_PER_CHUNK + j
            es = sorted(cases[tag], key=lambda r: r['widx'])
            assert [r['widx'] for r in es] == list(range(len(es)))
            key = keys[tag]
            ents = []
            for r in es:
                H = lst(f'({a}, {b})' for a, b in r['H'])
                if r['kind'] == 'direct':
                    v = '.direct'
                elif r['kind'] == 'pending':
                    v = '.pending'
                else:
                    lv = [u for u, _ in r['leaves']]
                    parts = []
                    for p in range(0, len(lv), CHL):
                        nm = f'l{idx:03d}_{r["widx"]}_{p // CHL}'
                        L.append(f'def {nm} : List (List Nat) := ' + lst(lst(str(2 * x if x > 0 else -2 * x + 1) for x in u) for u in lv[p:p + CHL]))
                        parts.append(nm)
                    assert '"' not in r['childof'] and ';' not in r['childof'] and '|' not in r['childof']
                    assert all(x != 0 for u in lv for x in u)
                    v = f'.split "{r["childof"]}" {r["fuel"]} (decLeaves ({" ++ ".join(parts)}))'
                ents.append(f'⟨{H}, {OPT[r["opt"]]}, {v}⟩')
            parts = []
            for p in range(0, len(ents), CH):
                nm = f'e{idx:03d}_{p // CH}'
                L.append(f'def {nm} : List Entry := ' + lst(ents[p:p + CH]))
                parts.append(nm)
            L.append(f'/-- `{tag}` -/')
            L.append(f'def c{idx:03d} : CaseRows := ⟨{", ".join(map(str, key))}, {" ++ ".join(parts) if parts else "[]"}⟩')
            names.append(f'c{idx:03d}')
            weight[f'c{idx:03d}'] = len(es) + sum(len(r.get('leaves', [])) for r in es)
        L += ['', f'def cases{ci:02d} : List CaseRows := ' + lst(names), '', 'end SB.Rooted.M5.Data']
        open(os.path.join(LEAN, 'Data', f'D{ci:02d}.lean'), 'w').write('\n'.join(L) + '\n')
        # check modules: consecutive cases grouped so that a module's weight (entries + split leaves) stays
        # under PART_WEIGHT; one `decide +kernel` per case. Memory grows over a module's declarations, so the
        # bound is per module (workstation, 2026-10-07: K00 as one module of 80 cases reached 9.3 GB).
        parts = []; cur = []; w = 0
        for nm in names:
            if cur and w + weight[nm] > PART_WEIGHT: parts.append(cur); cur = []; w = 0
            cur.append(nm); w += weight[nm]
        if cur: parts.append(cur)
        for pj, part in enumerate(parts):
            P = [f'/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.',
                 f'   Kernel checks of data chunk {ci:02d}, part {pj}: one `decide +kernel` per case. -/',
                 f'import RootedM5.Data.D{ci:02d}', 'import RootedM5.CheckDefs', '',
                 'namespace SB.Rooted.M5.Data', 'open SB.Rooted.M5', '']
            for nm in part:
                P += ['set_option maxRecDepth 100000 in', f'theorem {nm}_ok : caseOKB {nm} = true := by decide +kernel']
            P += ['', 'end SB.Rooted.M5.Data']
            open(os.path.join(LEAN, 'Checks', f'K{ci:02d}_{pj:02d}.lean'), 'w').write('\n'.join(P) + '\n')
        K = [f'/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.',
             f'   Kernel check of data chunk {ci:02d}: every case is a census case, its entries are the listed words of',
             f'   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.',
             f'   The per-case checks are in K{ci:02d}_00..K{ci:02d}_{len(parts) - 1:02d}. -/']
        K += [f'import RootedM5.Checks.K{ci:02d}_{pj:02d}' for pj in range(len(parts))]
        K += ['', 'namespace SB.Rooted.M5.Data', 'open SB.Rooted.M5', '',
              f'theorem cases{ci:02d}_ok : cases{ci:02d}.all caseOKB = true := by',
              f'  simp only [cases{ci:02d}, List.all_cons, List.all_nil, ' + ', '.join(f'{nm}_ok' for nm in names) + ', Bool.and_self]', '',
             'end SB.Rooted.M5.Data', '', f'#print axioms SB.Rooted.M5.Data.cases{ci:02d}_ok']
        open(os.path.join(LEAN, 'Checks', f'K{ci:02d}.lean'), 'w').write('\n'.join(K) + '\n')
    T = ['/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit. -/']
    T += [f'import RootedM5.Data.D{ci:02d}' for ci in range(nchunks)]
    T += ['', 'namespace SB.Rooted.M5', 'open SB.Rooted.M5.Data', '',
          '/-- The 781 census cases with their cubes (sorted list tags). -/',
          'def table : List CaseRows := ' + ' ++ '.join(f'cases{ci:02d}' for ci in range(nchunks)), '',
          '/-- The 23,886 cubes. -/',
          'def rows : List Row := table.flatMap CaseRows.rows', '', 'end SB.Rooted.M5']
    open(os.path.join(LEAN, 'Table.lean'), 'w').write('\n'.join(T) + '\n')
    C = ['/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.',
         '   `table_ok`: every case of the table passes `caseOKB` (from the per-chunk kernel checks). -/',
         'import RootedM5.Table']
    C += [f'import RootedM5.Checks.K{ci:02d}' for ci in range(nchunks)]
    C += ['', 'namespace SB.Rooted.M5', 'open SB.Rooted.M5.Data', '',
          'theorem table_ok : table.all caseOKB = true := by',
          '  rw [show table = ' + ' ++ '.join(f'cases{ci:02d}' for ci in range(nchunks)) + ' from rfl]',
          '  simp only [List.all_append, ' + ', '.join(f'cases{ci:02d}_ok' for ci in range(nchunks)) + ', Bool.and_self]',
          '', 'end SB.Rooted.M5', '', '#print axioms SB.Rooted.M5.table_ok']
    open(os.path.join(LEAN, 'Checks', 'All.lean'), 'w').write('\n'.join(C) + '\n')
    print(f'{nchunks} chunks, {len(rows)} entries')


if __name__ == '__main__':
    main()
