#!/usr/bin/env python3
"""M5: per-family listed-word identities, chunk by chunk (lean-sb/RootedM5/Fam/W_<tag>.lean, FamAll.lean).

For each of the 53 M0 certificates (the same data and the same 400-entry chunks as
m4_canon/gen_cover_data.py), writes the `wordEdges` lists of the listed words of every raw chunk
(`<tag>_lw<i>`), a `decide +kernel` per chunk (`chunkLW k <tag>_b<i> = <tag>_lw<i>`), and
`famLW_<tag> : (listedWords <tag>).map (wordEdges k) = LW_<tag>`. FamAll.lean collects them into `famH`
and proves `famH_spec` for every key of `famKeys`. Deterministic. usage: m5_gen_fam.py"""
import glob, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
M0 = os.path.join(HERE, '..', 'm0_hcover', 'data')
LEAN = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..', 'lean', 'sbsound'))
CH = 400


def pairs(k): return [(i, j) for i in range(k) for j in range(k) if i < j]


def word_edges(k, w): return [(i + 2, j + 2) for n, (i, j) in enumerate(pairs(k)) if w[n] == '1']


def lst(xs): return '[' + ', '.join(xs) + ']'


def main():
    os.makedirs(os.path.join(LEAN, 'RootedM5', 'Fam'), exist_ok=True)
    fams = []
    for f in sorted(glob.glob(os.path.join(M0, '*', 'cert_*.json'))):
        c = json.load(open(f)); k = c['family']['k']; comp = c['family']['comp']
        tag = 'k%d_c%d%d%d' % (k, comp[0], comp[1], comp[2])
        src = open(os.path.join(LEAN, 'RootedM4', 'CoverData', f'F_{tag}.lean')).read()
        m = re.search(rf'^def {tag} : SB\.Rooted\.M4\.Cover\.FamCert := (SB\.Rooted\.M4\.Cover\.rawCert [^\n]*)\n  (\([^\n]*\))\n  (\([^\n]*\))', src, re.M)
        head, pexpr, bexpr = m.group(1), m.group(2), m.group(3)
        bl = c['blockers']
        chunks = [bl[i:i + CH] for i in range(0, len(bl), CH)] or [[]]
        nb = len(re.findall(rf'^def {tag}_b\d+ ', src, re.M)); assert nb == len(chunks), (tag, nb, len(chunks))
        L = [f'/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.',
             f'   The listed words of the M0 certificate {tag}, as `wordEdges` lists, chunk by chunk. -/',
             f'import RootedM4.CoverData.F_{tag}', 'import RootedM5.FamDefs', '',
             'namespace SB.Rooted.M5.Fam', 'open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5', '']
        lws = []
        for i, ch in enumerate(chunks):
            ws = [word_edges(k, b['word']) for b in ch if b['kind'] == 'listed']
            if ws:
                L.append(f'def {tag}_lw{i} : List (List (Nat × Nat)) := ' + lst(lst(f'({a}, {b})' for a, b in w) for w in ws))
                rhs = f'{tag}_lw{i}'
            else:
                rhs = '[]'
            lws.append(rhs)
            L.append(f'theorem {tag}_ck{i} : chunkLW {k} {tag}_b{i} = {rhs} := by decide +kernel')
        L.append(f'def LW_{tag} : List (List (Nat × Nat)) := ' + ' ++ '.join(f'({x})' if x == '[]' else x for x in lws))
        L += [f'theorem famLW_{tag} : (listedWords {tag}).map (wordEdges {k}) = LW_{tag} := by',
              f'  show (listedWords ({head}\n    {pexpr}\n    {bexpr})).map (wordEdges {k}) = LW_{tag}',
              '  rw [listedWords_rawCert]',
              '  simp only [chunkLW_append, ' + ', '.join(f'{tag}_ck{i}' for i in range(len(chunks))) + ']',
              '  rfl', '', 'end SB.Rooted.M5.Fam']
        open(os.path.join(LEAN, 'RootedM5', 'Fam', f'W_{tag}.lean'), 'w').write('\n'.join(L) + '\n')
        fams.append((tag, k, comp))
    A = ['/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.',
         '   `famH k v8 v9 v10`: the `wordEdges` lists of the listed words of family (k, v8, v9, v10), and',
         '   `famH_spec`: it is `(listedWords (certOf …)).map (wordEdges k)` for every key of `famKeys`. -/']
    A += [f'import RootedM5.Fam.W_{t}' for t, _, _ in fams]
    A += ['import RootedM4.CoverData.All', '', 'namespace SB.Rooted.M5', 'open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5.Fam', '',
          'def famLWs : List ((Nat × Nat × Nat × Nat) × List (List (Nat × Nat))) := ' +
          lst(f'(({k}, {c[0]}, {c[1]}, {c[2]}), LW_{t})' for t, k, c in fams), '',
          'def famH (k v8 v9 v10 : Nat) : List (List (Nat × Nat)) :=',
          '  ((famLWs.find? (fun p => p.1 == (k, v8, v9, v10))).map (·.2)).getD []', '']
    for t, k, c in fams:
        key = f'{k} {c[0]} {c[1]} {c[2]}'
        A += [f'theorem famH_{t} : (listedWords (certOf {key})).map (wordEdges {k}) = famH {key} := by',
              f'  rw [show certOf {key} = {t} from rfl, show famH {key} = LW_{t} from rfl]',
              f'  exact famLW_{t}']
    A += ['', 'theorem famH_spec : ∀ key ∈ famKeys,',
          '    (listedWords (certOf key.1 key.2.1 key.2.2.1 key.2.2.2)).map (wordEdges key.1) =',
          '      famH key.1 key.2.1 key.2.2.1 key.2.2.2 := by',
          '  intro key hk',
          '  simp only [famKeys, List.mem_cons, List.not_mem_nil, or_false] at hk',
          '  rcases hk with ' + ' | '.join('rfl' for _ in fams),
          '  exacts [' + ', '.join(f'famH_{t}' for t, _, _ in fams) + ']', '', 'end SB.Rooted.M5', '',
          '#print axioms SB.Rooted.M5.famH_spec']
    open(os.path.join(LEAN, 'RootedM5', 'FamAll.lean'), 'w').write('\n'.join(A) + '\n')
    print(len(fams), 'families')


if __name__ == '__main__':
    main()
