#!/usr/bin/env python3
"""Generate a kernel-checked witness module (as Sbsound/Witness21Kernel.lean) from a deposited coloring.

usage: gen_witness_kernel.py WITNESS_FILE N S0 T0 S1 T1 NAME > Sbsound/WitnessNAMEKernel.lean

Deposited color 1 is Lean color 0 (no K_{S0,T0}), deposited color 2 is Lean color 1 (no K_{S1,T1}).
S0, S1 must be 2 or 3. The script checks the coloring itself before writing anything, and refuses if
it is not good: a module that fails to compile is the only other outcome it allows.
"""
import itertools, sys

wf, n, s0, t0, s1, t1, name = sys.argv[1], *map(int, sys.argv[2:7]), sys.argv[7]
E = {}
for l in open(wf):
    l = l.split('#')[0].split()
    if len(l) == 3:
        i, j, c = map(int, l); E[(i - 1, j - 1)] = c; E[(j - 1, i - 1)] = c
assert len(E) == n * (n - 1), f'{len(E)} ordered pairs, expected {n*(n-1)}'
assert set(E.values()) <= {1, 2}
for (s, t, col) in ((s0, t0, 1), (s1, t1, 2)):
    assert s in (2, 3)
    m = max(sum(1 for w in range(n) if w not in S and all(E[(u, w)] == col for u in S))
            for S in itertools.combinations(range(n), s))
    assert m < t, f'color {col}: an {s}-set has {m} common neighbours, limit {t - 1}'
M = 0
for (u, v), c in E.items():
    if c == 2: M |= 1 << (u * n + v)

def block(c, s, t):
    if s == 3:
        return f'''set_option maxRecDepth 100000 in
theorem cnt3_{c}{s}{t} : ∀ a b d : Vtx, a < b → b < d → cnt3 {c} a b d < {t} := by decide +kernel'''
    return f'''set_option maxRecDepth 100000 in
theorem cnt2_{c}{s}{t} : ∀ a b : Vtx, a < b → cnt2 {c} a b < {t} := by decide +kernel'''

def use(c, s, t):
    return f'(codegree_iff w {c} {s} {t}).mpr (smallCodegree{s}_of_cnt {c} {t} cnt{s}_{c}{s}{t})'

need3 = 3 in (s0, s1); need2 = 2 in (s0, s1)
out = f'''import Sbsound.Codegree

/-!
# A concrete witness: `R(K_{{{s0},{t0}}}, K_{{{s1},{t1}}}) > {n}`, checked by the kernel

Generated by `gen_witness_kernel.py` from the deposited coloring (its color 1 is color `0` here, its
color 2 is color `1`), with the same structure as `Witness21Kernel.lean`: the table is one natural
number `MASK` (bit `u * {n} + v` is set iff `{{u, v}}` has color `1`), `bb_symm` checks its symmetry, and
common neighbours are counted over sorted tuples. Every evaluation is `decide +kernel`.
-/

namespace SB.Witness{name}

open SB

abbrev Vtx := Fin {n}

def MASK : Nat := {M}

def bb (u v : Vtx) : Bool := Nat.testBit MASK (u.val * {n} + v.val)

set_option maxRecDepth 100000 in
theorem bb_symm : ∀ u v : Vtx, bb u v = bb v u := by decide +kernel

def w : EColouring {n} 2 := fun e => cond (bb (ofLex e.val).1 (ofLex e.val).2) 1 0

lemma eval_w_mkEdge {{u v : Vtx}} (h : u ≠ v) : w (mkEdge u v h) = cond (bb u v) 1 0 := by
  rcases lt_or_gt_of_ne h with hl | hg
  · rw [mkEdge_pos h hl]; rfl
  · rw [mkEdge_neg h hg, bb_symm u v]; rfl

lemma eq_c_iff {{c : Fin 2}} (b : Bool) :
    (cond b 1 0 = c) ↔ (decide b = decide (c == 1)) := by
  revert b
  fin_cases c <;> intros b <;> cases b <;> simp [Fin.isValue]

def isC (c : Fin 2) (u v : Vtx) : Bool :=
  decide (u ≠ v) && decide (bb u v = (c == 1))

lemma colourRel_iff_isC (c : Fin 2) (u v : Vtx) :
    colourRel w c u v ↔ isC c u v = true := by
  constructor
  · rintro ⟨hne, hc⟩
    rw [eval_w_mkEdge hne, eq_c_iff] at hc
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq]
    exact ⟨hne, by simpa using hc⟩
  · intro h
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq] at h
    refine ⟨h.1, ?_⟩
    rw [eval_w_mkEdge h.1]
    exact (eq_c_iff _).mpr (by simpa using h.2)
'''
if need3:
    out += f'''
def cnt3 (c : Fin 2) (a b d : Vtx) : Nat :=
  (List.finRange {n}).countP fun v => decide (v ≠ a) && decide (v ≠ b) && decide (v ≠ d)
    && isC c a v && isC c b v && isC c d v

theorem card_commonNbrs3 (c : Fin 2) (a b d : Vtx) :
    (commonNbrs w c {{a, b, d}}).card = cnt3 c a b d := by
  rw [commonNbrs, Finset.card_def, Finset.filter_val, ← Multiset.countP_eq_card_filter,
    Finset.val_univ_fin, Multiset.coe_countP, cnt3]
  apply List.countP_congr
  intro v _
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or, forall_eq_or_imp, forall_eq,
    colourRel_iff_isC, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  tauto

theorem triple_sorted {{x y z : Vtx}} (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z) :
    ∃ a b d : Vtx, a < b ∧ b < d ∧ ({{x, y, z}} : Finset Vtx) = {{a, b, d}} := by
  rcases lt_or_gt_of_ne hxy with h1 | h1 <;>
  rcases lt_or_gt_of_ne hxz with h2 | h2 <;>
  rcases lt_or_gt_of_ne hyz with h3 | h3
  all_goals first
    | exact ⟨x, y, z, by assumption, by assumption, rfl⟩
    | exact ⟨x, z, y, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨y, x, z, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨y, z, x, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨z, x, y, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨z, y, x, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩

theorem smallCodegree3_of_cnt (c : Fin 2) (t : ℕ)
    (h : ∀ a b d : Vtx, a < b → b < d → cnt3 c a b d < t) : SmallCodegree w c 3 t := by
  intro S hS
  obtain ⟨x, y, z, hxy, hxz, hyz, rfl⟩ :=
    Finset.card_eq_three.mp (Finset.mem_powersetCard.mp hS).2
  obtain ⟨a, b, d, hab, hbd, he⟩ := triple_sorted hxy hxz hyz
  rw [he, card_commonNbrs3]
  exact h a b d hab hbd
'''
if need2:
    out += f'''
def cnt2 (c : Fin 2) (a b : Vtx) : Nat :=
  (List.finRange {n}).countP fun v => decide (v ≠ a) && decide (v ≠ b) && isC c a v && isC c b v

theorem card_commonNbrs2 (c : Fin 2) (a b : Vtx) :
    (commonNbrs w c {{a, b}}).card = cnt2 c a b := by
  rw [commonNbrs, Finset.card_def, Finset.filter_val, ← Multiset.countP_eq_card_filter,
    Finset.val_univ_fin, Multiset.coe_countP, cnt2]
  apply List.countP_congr
  intro v _
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or, forall_eq_or_imp, forall_eq,
    colourRel_iff_isC, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  tauto

theorem smallCodegree2_of_cnt (c : Fin 2) (t : ℕ)
    (h : ∀ a b : Vtx, a < b → cnt2 c a b < t) : SmallCodegree w c 2 t := by
  intro S hS
  obtain ⟨x, y, hxy, rfl⟩ := Finset.card_eq_two.mp (Finset.mem_powersetCard.mp hS).2
  rcases lt_or_gt_of_ne hxy with hl | hg
  · rw [card_commonNbrs2]; exact h x y hl
  · rw [Finset.pair_comm, card_commonNbrs2]; exact h y x hg
'''
out += f'''
{block(0, s0, t0)}

{block(1, s1, t1)}

/-- **The witness theorem, kernel-checked.** `w` has no `K_{{{s0},{t0}}}` in color `0` and no `K_{{{s1},{t1}}}` in
color `1`, so `R(K_{{{s0},{t0}}}, K_{{{s1},{t1}}}) > {n}`. -/
theorem witness_kernel : NoKst w 0 {s0} {t0} ∧ NoKst w 1 {s1} {t1} :=
  ⟨{use(0, s0, t0)},
   {use(1, s1, t1)}⟩

end SB.Witness{name}

#print axioms SB.Witness{name}.witness_kernel
'''
sys.stdout.write(out)
