/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit. -/
import RootedM4.CoverData.F_k10_c0100
import RootedM4.CoverData.F_k10_c019
import RootedM4.CoverData.F_k10_c028
import RootedM4.CoverData.F_k10_c037
import RootedM4.CoverData.F_k10_c046
import RootedM4.CoverData.F_k10_c055
import RootedM4.CoverData.F_k10_c064
import RootedM4.CoverData.F_k10_c073
import RootedM4.CoverData.F_k10_c082
import RootedM4.CoverData.F_k10_c091
import RootedM4.CoverData.F_k8_c008
import RootedM4.CoverData.F_k8_c017
import RootedM4.CoverData.F_k8_c026
import RootedM4.CoverData.F_k8_c035
import RootedM4.CoverData.F_k8_c044
import RootedM4.CoverData.F_k8_c053
import RootedM4.CoverData.F_k8_c062
import RootedM4.CoverData.F_k8_c071
import RootedM4.CoverData.F_k8_c080
import RootedM4.CoverData.F_k8_c107
import RootedM4.CoverData.F_k8_c116
import RootedM4.CoverData.F_k8_c125
import RootedM4.CoverData.F_k8_c134
import RootedM4.CoverData.F_k8_c143
import RootedM4.CoverData.F_k8_c152
import RootedM4.CoverData.F_k8_c161
import RootedM4.CoverData.F_k8_c170
import RootedM4.CoverData.F_k8_c206
import RootedM4.CoverData.F_k8_c215
import RootedM4.CoverData.F_k8_c224
import RootedM4.CoverData.F_k8_c233
import RootedM4.CoverData.F_k8_c242
import RootedM4.CoverData.F_k8_c251
import RootedM4.CoverData.F_k8_c260
import RootedM4.CoverData.F_k8_c305
import RootedM4.CoverData.F_k8_c314
import RootedM4.CoverData.F_k8_c323
import RootedM4.CoverData.F_k8_c332
import RootedM4.CoverData.F_k8_c341
import RootedM4.CoverData.F_k8_c350
import RootedM4.CoverData.F_k8_c404
import RootedM4.CoverData.F_k8_c413
import RootedM4.CoverData.F_k8_c422
import RootedM4.CoverData.F_k8_c431
import RootedM4.CoverData.F_k8_c440
import RootedM4.CoverData.F_k8_c503
import RootedM4.CoverData.F_k8_c512
import RootedM4.CoverData.F_k8_c521
import RootedM4.CoverData.F_k8_c530
import RootedM4.CoverData.F_k8_c602
import RootedM4.CoverData.F_k8_c611
import RootedM4.CoverData.F_k8_c620
import RootedM4.CoverData.F_k9_c090

namespace SB.Rooted.M4.CoverData

/-- The 53 M0 family certificates. -/
def allCerts : List SB.Rooted.M4.Cover.FamCert := [k10_c0100, k10_c019, k10_c028, k10_c037, k10_c046, k10_c055, k10_c064, k10_c073, k10_c082, k10_c091, k8_c008, k8_c017, k8_c026, k8_c035, k8_c044, k8_c053, k8_c062, k8_c071, k8_c080, k8_c107, k8_c116, k8_c125, k8_c134, k8_c143, k8_c152, k8_c161, k8_c170, k8_c206, k8_c215, k8_c224, k8_c233, k8_c242, k8_c251, k8_c260, k8_c305, k8_c314, k8_c323, k8_c332, k8_c341, k8_c350, k8_c404, k8_c413, k8_c422, k8_c431, k8_c440, k8_c503, k8_c512, k8_c521, k8_c530, k8_c602, k8_c611, k8_c620, k9_c090]

/-- Their keys `(k, v8, v9, v10)`, in the same order. -/
def famKeys : List (Nat × Nat × Nat × Nat) := [(10, 0, 10, 0), (10, 0, 1, 9), (10, 0, 2, 8), (10, 0, 3, 7), (10, 0, 4, 6), (10, 0, 5, 5), (10, 0, 6, 4), (10, 0, 7, 3), (10, 0, 8, 2), (10, 0, 9, 1), (8, 0, 0, 8), (8, 0, 1, 7), (8, 0, 2, 6), (8, 0, 3, 5), (8, 0, 4, 4), (8, 0, 5, 3), (8, 0, 6, 2), (8, 0, 7, 1), (8, 0, 8, 0), (8, 1, 0, 7), (8, 1, 1, 6), (8, 1, 2, 5), (8, 1, 3, 4), (8, 1, 4, 3), (8, 1, 5, 2), (8, 1, 6, 1), (8, 1, 7, 0), (8, 2, 0, 6), (8, 2, 1, 5), (8, 2, 2, 4), (8, 2, 3, 3), (8, 2, 4, 2), (8, 2, 5, 1), (8, 2, 6, 0), (8, 3, 0, 5), (8, 3, 1, 4), (8, 3, 2, 3), (8, 3, 3, 2), (8, 3, 4, 1), (8, 3, 5, 0), (8, 4, 0, 4), (8, 4, 1, 3), (8, 4, 2, 2), (8, 4, 3, 1), (8, 4, 4, 0), (8, 5, 0, 3), (8, 5, 1, 2), (8, 5, 2, 1), (8, 5, 3, 0), (8, 6, 0, 2), (8, 6, 1, 1), (8, 6, 2, 0), (9, 0, 9, 0)]

/-- The certificate of family `(k, v8, v9, v10)`. -/
def certOf (k v8 v9 v10 : Nat) : SB.Rooted.M4.Cover.FamCert :=
  allCerts.getD (famKeys.idxOf (k, v8, v9, v10)) k10_c0100

end SB.Rooted.M4.CoverData
