/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py from m0_hcover/data/k10_c046/cert_k10_c046.json
   (cnf_sha256 57d11ac70d3e307bfd9ac5a3f92b61e2545cd10ab9d600ddcd57feca77a5337c). Do not edit. -/
import RootedM4.CoverBase

namespace SB.Rooted.M4.CoverData

def k10_c046_p0 : List (List Nat) := [[1,0,2,3,4,5,6,7,8,9], [2,1,0,3,4,5,6,7,8,9], [3,1,2,0,4,5,6,7,8,9], [0,2,1,3,4,5,6,7,8,9], [0,3,2,1,4,5,6,7,8,9], [0,1,3,2,4,5,6,7,8,9], [0,1,2,3,5,4,6,7,8,9], [0,1,2,3,6,5,4,7,8,9], [0,1,2,3,7,5,6,4,8,9], [0,1,2,3,8,5,6,7,4,9], [0,1,2,3,9,5,6,7,8,4], [0,1,2,3,4,6,5,7,8,9], [0,1,2,3,4,7,6,5,8,9], [0,1,2,3,4,8,6,7,5,9], [0,1,2,3,4,9,6,7,8,5], [0,1,2,3,4,5,7,6,8,9], [0,1,2,3,4,5,8,7,6,9], [0,1,2,3,4,5,9,7,8,6], [0,1,2,3,4,5,6,8,7,9], [0,1,2,3,4,5,6,9,8,7], [0,1,2,3,4,5,6,7,9,8]]
def k10_c046_b0 : List (Nat × Nat) := []

def k10_c046 : SB.Rooted.M4.Cover.FamCert := SB.Rooted.M4.Cover.rawCert 10 0 4 6
  (k10_c046_p0)
  (k10_c046_b0)

end SB.Rooted.M4.CoverData
