/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py from m0_hcover/data/k10_c055/cert_k10_c055.json
   (cnf_sha256 f6c137621d31b945f48e5560922d59c9e7f36886a4aeb43e06b9690c4e310356). Do not edit. -/
import RootedM4.CoverBase

namespace SB.Rooted.M4.CoverData

def k10_c055_p0 : List (List Nat) := [[1,0,2,3,4,5,6,7,8,9], [2,1,0,3,4,5,6,7,8,9], [3,1,2,0,4,5,6,7,8,9], [4,1,2,3,0,5,6,7,8,9], [0,2,1,3,4,5,6,7,8,9], [0,3,2,1,4,5,6,7,8,9], [0,4,2,3,1,5,6,7,8,9], [0,1,3,2,4,5,6,7,8,9], [0,1,4,3,2,5,6,7,8,9], [0,1,2,4,3,5,6,7,8,9], [0,1,2,3,4,6,5,7,8,9], [0,1,2,3,4,7,6,5,8,9], [0,1,2,3,4,8,6,7,5,9], [0,1,2,3,4,9,6,7,8,5], [0,1,2,3,4,5,7,6,8,9], [0,1,2,3,4,5,8,7,6,9], [0,1,2,3,4,5,9,7,8,6], [0,1,2,3,4,5,6,8,7,9], [0,1,2,3,4,5,6,9,8,7], [0,1,2,3,4,5,6,7,9,8]]
def k10_c055_b0 : List (Nat × Nat) := []

def k10_c055 : SB.Rooted.M4.Cover.FamCert := SB.Rooted.M4.Cover.rawCert 10 0 5 5
  (k10_c055_p0)
  (k10_c055_b0)

end SB.Rooted.M4.CoverData
