/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   `table_ok`: every case of the table passes `caseOKB` (from the per-chunk kernel checks). -/
import RootedM5.Table
import RootedM5.Checks.K00
import RootedM5.Checks.K01
import RootedM5.Checks.K02
import RootedM5.Checks.K03
import RootedM5.Checks.K04
import RootedM5.Checks.K05
import RootedM5.Checks.K06
import RootedM5.Checks.K07
import RootedM5.Checks.K08
import RootedM5.Checks.K09

namespace SB.Rooted.M5
open SB.Rooted.M5.Data

theorem table_ok : table.all caseOKB = true := by
  rw [show table = cases00 ++ cases01 ++ cases02 ++ cases03 ++ cases04 ++ cases05 ++ cases06 ++ cases07 ++ cases08 ++ cases09 from rfl]
  simp only [List.all_append, cases00_ok, cases01_ok, cases02_ok, cases03_ok, cases04_ok, cases05_ok, cases06_ok, cases07_ok, cases08_ok, cases09_ok, Bool.and_self]

end SB.Rooted.M5

#print axioms SB.Rooted.M5.table_ok
