/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 00: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K00_00..K00_10. -/
import RootedM5.Checks.K00_00
import RootedM5.Checks.K00_01
import RootedM5.Checks.K00_02
import RootedM5.Checks.K00_03
import RootedM5.Checks.K00_04
import RootedM5.Checks.K00_05
import RootedM5.Checks.K00_06
import RootedM5.Checks.K00_07
import RootedM5.Checks.K00_08
import RootedM5.Checks.K00_09
import RootedM5.Checks.K00_10

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases00_ok : cases00.all caseOKB = true := by
  simp only [cases00, List.all_cons, List.all_nil, c000_ok, c001_ok, c002_ok, c003_ok, c004_ok, c005_ok, c006_ok, c007_ok, c008_ok, c009_ok, c010_ok, c011_ok, c012_ok, c013_ok, c014_ok, c015_ok, c016_ok, c017_ok, c018_ok, c019_ok, c020_ok, c021_ok, c022_ok, c023_ok, c024_ok, c025_ok, c026_ok, c027_ok, c028_ok, c029_ok, c030_ok, c031_ok, c032_ok, c033_ok, c034_ok, c035_ok, c036_ok, c037_ok, c038_ok, c039_ok, c040_ok, c041_ok, c042_ok, c043_ok, c044_ok, c045_ok, c046_ok, c047_ok, c048_ok, c049_ok, c050_ok, c051_ok, c052_ok, c053_ok, c054_ok, c055_ok, c056_ok, c057_ok, c058_ok, c059_ok, c060_ok, c061_ok, c062_ok, c063_ok, c064_ok, c065_ok, c066_ok, c067_ok, c068_ok, c069_ok, c070_ok, c071_ok, c072_ok, c073_ok, c074_ok, c075_ok, c076_ok, c077_ok, c078_ok, c079_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases00_ok
