/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 7: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c027_ok : caseOKB c027 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c028_ok : caseOKB c028 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c029_ok : caseOKB c029 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c030_ok : caseOKB c030 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c031_ok : caseOKB c031 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c032_ok : caseOKB c032 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c033_ok : caseOKB c033 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c034_ok : caseOKB c034 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c035_ok : caseOKB c035 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c036_ok : caseOKB c036 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c037_ok : caseOKB c037 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c038_ok : caseOKB c038 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c039_ok : caseOKB c039 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c040_ok : caseOKB c040 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c041_ok : caseOKB c041 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c042_ok : caseOKB c042 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c043_ok : caseOKB c043 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c044_ok : caseOKB c044 = true := by decide +kernel

end SB.Rooted.M5.Data
