/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 4: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c018_ok : caseOKB c018 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c019_ok : caseOKB c019 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c020_ok : caseOKB c020 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c021_ok : caseOKB c021 = true := by decide +kernel

end SB.Rooted.M5.Data
