/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 5: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c022_ok : caseOKB c022 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c023_ok : caseOKB c023 = true := by decide +kernel

end SB.Rooted.M5.Data
