/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c008_ok : caseOKB c008 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c009_ok : caseOKB c009 = true := by decide +kernel

end SB.Rooted.M5.Data
