/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 9: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c051_ok : caseOKB c051 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c052_ok : caseOKB c052 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c053_ok : caseOKB c053 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c054_ok : caseOKB c054 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c055_ok : caseOKB c055 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c056_ok : caseOKB c056 = true := by decide +kernel

end SB.Rooted.M5.Data
