/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 8: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c045_ok : caseOKB c045 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c046_ok : caseOKB c046 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c047_ok : caseOKB c047 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c048_ok : caseOKB c048 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c049_ok : caseOKB c049 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c050_ok : caseOKB c050 = true := by decide +kernel

end SB.Rooted.M5.Data
