/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 2: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c010_ok : caseOKB c010 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c011_ok : caseOKB c011 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c012_ok : caseOKB c012 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c013_ok : caseOKB c013 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c014_ok : caseOKB c014 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c015_ok : caseOKB c015 = true := by decide +kernel

end SB.Rooted.M5.Data
