/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 6: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c024_ok : caseOKB c024 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c025_ok : caseOKB c025 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c026_ok : caseOKB c026 = true := by decide +kernel

end SB.Rooted.M5.Data
