/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 10: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c057_ok : caseOKB c057 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c058_ok : caseOKB c058 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c059_ok : caseOKB c059 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c060_ok : caseOKB c060 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c061_ok : caseOKB c061 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c062_ok : caseOKB c062 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c063_ok : caseOKB c063 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c064_ok : caseOKB c064 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c065_ok : caseOKB c065 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c066_ok : caseOKB c066 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c067_ok : caseOKB c067 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c068_ok : caseOKB c068 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c069_ok : caseOKB c069 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c070_ok : caseOKB c070 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c071_ok : caseOKB c071 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c072_ok : caseOKB c072 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c073_ok : caseOKB c073 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c074_ok : caseOKB c074 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c075_ok : caseOKB c075 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c076_ok : caseOKB c076 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c077_ok : caseOKB c077 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c078_ok : caseOKB c078 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c079_ok : caseOKB c079 = true := by decide +kernel

end SB.Rooted.M5.Data
