/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 00, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D00
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c000_ok : caseOKB c000 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c001_ok : caseOKB c001 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c002_ok : caseOKB c002 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c003_ok : caseOKB c003 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c004_ok : caseOKB c004 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c005_ok : caseOKB c005 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c006_ok : caseOKB c006 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c007_ok : caseOKB c007 = true := by decide +kernel

end SB.Rooted.M5.Data
