/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 01: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K01_00..K01_21. -/
import RootedM5.Checks.K01_00
import RootedM5.Checks.K01_01
import RootedM5.Checks.K01_02
import RootedM5.Checks.K01_03
import RootedM5.Checks.K01_04
import RootedM5.Checks.K01_05
import RootedM5.Checks.K01_06
import RootedM5.Checks.K01_07
import RootedM5.Checks.K01_08
import RootedM5.Checks.K01_09
import RootedM5.Checks.K01_10
import RootedM5.Checks.K01_11
import RootedM5.Checks.K01_12
import RootedM5.Checks.K01_13
import RootedM5.Checks.K01_14
import RootedM5.Checks.K01_15
import RootedM5.Checks.K01_16
import RootedM5.Checks.K01_17
import RootedM5.Checks.K01_18
import RootedM5.Checks.K01_19
import RootedM5.Checks.K01_20
import RootedM5.Checks.K01_21

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases01_ok : cases01.all caseOKB = true := by
  simp only [cases01, List.all_cons, List.all_nil, c080_ok, c081_ok, c082_ok, c083_ok, c084_ok, c085_ok, c086_ok, c087_ok, c088_ok, c089_ok, c090_ok, c091_ok, c092_ok, c093_ok, c094_ok, c095_ok, c096_ok, c097_ok, c098_ok, c099_ok, c100_ok, c101_ok, c102_ok, c103_ok, c104_ok, c105_ok, c106_ok, c107_ok, c108_ok, c109_ok, c110_ok, c111_ok, c112_ok, c113_ok, c114_ok, c115_ok, c116_ok, c117_ok, c118_ok, c119_ok, c120_ok, c121_ok, c122_ok, c123_ok, c124_ok, c125_ok, c126_ok, c127_ok, c128_ok, c129_ok, c130_ok, c131_ok, c132_ok, c133_ok, c134_ok, c135_ok, c136_ok, c137_ok, c138_ok, c139_ok, c140_ok, c141_ok, c142_ok, c143_ok, c144_ok, c145_ok, c146_ok, c147_ok, c148_ok, c149_ok, c150_ok, c151_ok, c152_ok, c153_ok, c154_ok, c155_ok, c156_ok, c157_ok, c158_ok, c159_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases01_ok
