/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 11: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c107_ok : caseOKB c107 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c108_ok : caseOKB c108 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c109_ok : caseOKB c109 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c110_ok : caseOKB c110 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c111_ok : caseOKB c111 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c112_ok : caseOKB c112 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c113_ok : caseOKB c113 = true := by decide +kernel

end SB.Rooted.M5.Data
