/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c084_ok : caseOKB c084 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c085_ok : caseOKB c085 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c086_ok : caseOKB c086 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c087_ok : caseOKB c087 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c088_ok : caseOKB c088 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c089_ok : caseOKB c089 = true := by decide +kernel

end SB.Rooted.M5.Data
