/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 4: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c092_ok : caseOKB c092 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c093_ok : caseOKB c093 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c094_ok : caseOKB c094 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c095_ok : caseOKB c095 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c096_ok : caseOKB c096 = true := by decide +kernel

end SB.Rooted.M5.Data
