/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c080_ok : caseOKB c080 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c081_ok : caseOKB c081 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c082_ok : caseOKB c082 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c083_ok : caseOKB c083 = true := by decide +kernel

end SB.Rooted.M5.Data
