/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 21: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c156_ok : caseOKB c156 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c157_ok : caseOKB c157 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c158_ok : caseOKB c158 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c159_ok : caseOKB c159 = true := by decide +kernel

end SB.Rooted.M5.Data
