/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 19: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c153_ok : caseOKB c153 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c154_ok : caseOKB c154 = true := by decide +kernel

end SB.Rooted.M5.Data
