/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 7: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c099_ok : caseOKB c099 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c100_ok : caseOKB c100 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c101_ok : caseOKB c101 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c102_ok : caseOKB c102 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c103_ok : caseOKB c103 = true := by decide +kernel

end SB.Rooted.M5.Data
