/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 14: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c120_ok : caseOKB c120 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c121_ok : caseOKB c121 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c122_ok : caseOKB c122 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c123_ok : caseOKB c123 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c124_ok : caseOKB c124 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c125_ok : caseOKB c125 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c126_ok : caseOKB c126 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c127_ok : caseOKB c127 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c128_ok : caseOKB c128 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c129_ok : caseOKB c129 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c130_ok : caseOKB c130 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c131_ok : caseOKB c131 = true := by decide +kernel

end SB.Rooted.M5.Data
