/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 18: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c141_ok : caseOKB c141 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c142_ok : caseOKB c142 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c143_ok : caseOKB c143 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c144_ok : caseOKB c144 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c145_ok : caseOKB c145 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c146_ok : caseOKB c146 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c147_ok : caseOKB c147 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c148_ok : caseOKB c148 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c149_ok : caseOKB c149 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c150_ok : caseOKB c150 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c151_ok : caseOKB c151 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c152_ok : caseOKB c152 = true := by decide +kernel

end SB.Rooted.M5.Data
