/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 01, part 15: one `decide +kernel` per case. -/
import RootedM5.Data.D01
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c132_ok : caseOKB c132 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c133_ok : caseOKB c133 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c134_ok : caseOKB c134 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c135_ok : caseOKB c135 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c136_ok : caseOKB c136 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c137_ok : caseOKB c137 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c138_ok : caseOKB c138 = true := by decide +kernel

end SB.Rooted.M5.Data
