/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 02: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K02_00..K02_27. -/
import RootedM5.Checks.K02_00
import RootedM5.Checks.K02_01
import RootedM5.Checks.K02_02
import RootedM5.Checks.K02_03
import RootedM5.Checks.K02_04
import RootedM5.Checks.K02_05
import RootedM5.Checks.K02_06
import RootedM5.Checks.K02_07
import RootedM5.Checks.K02_08
import RootedM5.Checks.K02_09
import RootedM5.Checks.K02_10
import RootedM5.Checks.K02_11
import RootedM5.Checks.K02_12
import RootedM5.Checks.K02_13
import RootedM5.Checks.K02_14
import RootedM5.Checks.K02_15
import RootedM5.Checks.K02_16
import RootedM5.Checks.K02_17
import RootedM5.Checks.K02_18
import RootedM5.Checks.K02_19
import RootedM5.Checks.K02_20
import RootedM5.Checks.K02_21
import RootedM5.Checks.K02_22
import RootedM5.Checks.K02_23
import RootedM5.Checks.K02_24
import RootedM5.Checks.K02_25
import RootedM5.Checks.K02_26
import RootedM5.Checks.K02_27

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases02_ok : cases02.all caseOKB = true := by
  simp only [cases02, List.all_cons, List.all_nil, c160_ok, c161_ok, c162_ok, c163_ok, c164_ok, c165_ok, c166_ok, c167_ok, c168_ok, c169_ok, c170_ok, c171_ok, c172_ok, c173_ok, c174_ok, c175_ok, c176_ok, c177_ok, c178_ok, c179_ok, c180_ok, c181_ok, c182_ok, c183_ok, c184_ok, c185_ok, c186_ok, c187_ok, c188_ok, c189_ok, c190_ok, c191_ok, c192_ok, c193_ok, c194_ok, c195_ok, c196_ok, c197_ok, c198_ok, c199_ok, c200_ok, c201_ok, c202_ok, c203_ok, c204_ok, c205_ok, c206_ok, c207_ok, c208_ok, c209_ok, c210_ok, c211_ok, c212_ok, c213_ok, c214_ok, c215_ok, c216_ok, c217_ok, c218_ok, c219_ok, c220_ok, c221_ok, c222_ok, c223_ok, c224_ok, c225_ok, c226_ok, c227_ok, c228_ok, c229_ok, c230_ok, c231_ok, c232_ok, c233_ok, c234_ok, c235_ok, c236_ok, c237_ok, c238_ok, c239_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases02_ok
