/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 19: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c200_ok : caseOKB c200 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c201_ok : caseOKB c201 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c202_ok : caseOKB c202 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c203_ok : caseOKB c203 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c204_ok : caseOKB c204 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c205_ok : caseOKB c205 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c206_ok : caseOKB c206 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c207_ok : caseOKB c207 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c208_ok : caseOKB c208 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c209_ok : caseOKB c209 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c210_ok : caseOKB c210 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c211_ok : caseOKB c211 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c212_ok : caseOKB c212 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c213_ok : caseOKB c213 = true := by decide +kernel

end SB.Rooted.M5.Data
