/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 14: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c184_ok : caseOKB c184 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c185_ok : caseOKB c185 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c186_ok : caseOKB c186 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c187_ok : caseOKB c187 = true := by decide +kernel

end SB.Rooted.M5.Data
