/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 20: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c214_ok : caseOKB c214 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c215_ok : caseOKB c215 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c216_ok : caseOKB c216 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c217_ok : caseOKB c217 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c218_ok : caseOKB c218 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c219_ok : caseOKB c219 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c220_ok : caseOKB c220 = true := by decide +kernel

end SB.Rooted.M5.Data
