/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 18: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c196_ok : caseOKB c196 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c197_ok : caseOKB c197 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c198_ok : caseOKB c198 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c199_ok : caseOKB c199 = true := by decide +kernel

end SB.Rooted.M5.Data
