/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 24: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c224_ok : caseOKB c224 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c225_ok : caseOKB c225 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c226_ok : caseOKB c226 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c227_ok : caseOKB c227 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c228_ok : caseOKB c228 = true := by decide +kernel

end SB.Rooted.M5.Data
