/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 10: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c177_ok : caseOKB c177 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c178_ok : caseOKB c178 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c179_ok : caseOKB c179 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c180_ok : caseOKB c180 = true := by decide +kernel

end SB.Rooted.M5.Data
