/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 17: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c190_ok : caseOKB c190 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c191_ok : caseOKB c191 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c192_ok : caseOKB c192 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c193_ok : caseOKB c193 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c194_ok : caseOKB c194 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c195_ok : caseOKB c195 = true := by decide +kernel

end SB.Rooted.M5.Data
