/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 4: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c165_ok : caseOKB c165 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c166_ok : caseOKB c166 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c167_ok : caseOKB c167 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c168_ok : caseOKB c168 = true := by decide +kernel

end SB.Rooted.M5.Data
