/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 02, part 27: one `decide +kernel` per case. -/
import RootedM5.Data.D02
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c231_ok : caseOKB c231 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c232_ok : caseOKB c232 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c233_ok : caseOKB c233 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c234_ok : caseOKB c234 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c235_ok : caseOKB c235 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c236_ok : caseOKB c236 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c237_ok : caseOKB c237 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c238_ok : caseOKB c238 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c239_ok : caseOKB c239 = true := by decide +kernel

end SB.Rooted.M5.Data
