/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 03: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K03_00..K03_17. -/
import RootedM5.Checks.K03_00
import RootedM5.Checks.K03_01
import RootedM5.Checks.K03_02
import RootedM5.Checks.K03_03
import RootedM5.Checks.K03_04
import RootedM5.Checks.K03_05
import RootedM5.Checks.K03_06
import RootedM5.Checks.K03_07
import RootedM5.Checks.K03_08
import RootedM5.Checks.K03_09
import RootedM5.Checks.K03_10
import RootedM5.Checks.K03_11
import RootedM5.Checks.K03_12
import RootedM5.Checks.K03_13
import RootedM5.Checks.K03_14
import RootedM5.Checks.K03_15
import RootedM5.Checks.K03_16
import RootedM5.Checks.K03_17

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases03_ok : cases03.all caseOKB = true := by
  simp only [cases03, List.all_cons, List.all_nil, c240_ok, c241_ok, c242_ok, c243_ok, c244_ok, c245_ok, c246_ok, c247_ok, c248_ok, c249_ok, c250_ok, c251_ok, c252_ok, c253_ok, c254_ok, c255_ok, c256_ok, c257_ok, c258_ok, c259_ok, c260_ok, c261_ok, c262_ok, c263_ok, c264_ok, c265_ok, c266_ok, c267_ok, c268_ok, c269_ok, c270_ok, c271_ok, c272_ok, c273_ok, c274_ok, c275_ok, c276_ok, c277_ok, c278_ok, c279_ok, c280_ok, c281_ok, c282_ok, c283_ok, c284_ok, c285_ok, c286_ok, c287_ok, c288_ok, c289_ok, c290_ok, c291_ok, c292_ok, c293_ok, c294_ok, c295_ok, c296_ok, c297_ok, c298_ok, c299_ok, c300_ok, c301_ok, c302_ok, c303_ok, c304_ok, c305_ok, c306_ok, c307_ok, c308_ok, c309_ok, c310_ok, c311_ok, c312_ok, c313_ok, c314_ok, c315_ok, c316_ok, c317_ok, c318_ok, c319_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases03_ok
