/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 11: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c268_ok : caseOKB c268 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c269_ok : caseOKB c269 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c270_ok : caseOKB c270 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c271_ok : caseOKB c271 = true := by decide +kernel

end SB.Rooted.M5.Data
