/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 10: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c259_ok : caseOKB c259 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c260_ok : caseOKB c260 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c261_ok : caseOKB c261 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c262_ok : caseOKB c262 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c263_ok : caseOKB c263 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c264_ok : caseOKB c264 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c265_ok : caseOKB c265 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c266_ok : caseOKB c266 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c267_ok : caseOKB c267 = true := by decide +kernel

end SB.Rooted.M5.Data
