/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 14: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c274_ok : caseOKB c274 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c275_ok : caseOKB c275 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c276_ok : caseOKB c276 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c277_ok : caseOKB c277 = true := by decide +kernel

end SB.Rooted.M5.Data
