/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 16: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c279_ok : caseOKB c279 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c280_ok : caseOKB c280 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c281_ok : caseOKB c281 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c282_ok : caseOKB c282 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c283_ok : caseOKB c283 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c284_ok : caseOKB c284 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c285_ok : caseOKB c285 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c286_ok : caseOKB c286 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c287_ok : caseOKB c287 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c288_ok : caseOKB c288 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c289_ok : caseOKB c289 = true := by decide +kernel

end SB.Rooted.M5.Data
