/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c240_ok : caseOKB c240 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c241_ok : caseOKB c241 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c242_ok : caseOKB c242 = true := by decide +kernel

end SB.Rooted.M5.Data
