/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 17: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c290_ok : caseOKB c290 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c291_ok : caseOKB c291 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c292_ok : caseOKB c292 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c293_ok : caseOKB c293 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c294_ok : caseOKB c294 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c295_ok : caseOKB c295 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c296_ok : caseOKB c296 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c297_ok : caseOKB c297 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c298_ok : caseOKB c298 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c299_ok : caseOKB c299 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c300_ok : caseOKB c300 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c301_ok : caseOKB c301 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c302_ok : caseOKB c302 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c303_ok : caseOKB c303 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c304_ok : caseOKB c304 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c305_ok : caseOKB c305 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c306_ok : caseOKB c306 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c307_ok : caseOKB c307 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c308_ok : caseOKB c308 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c309_ok : caseOKB c309 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c310_ok : caseOKB c310 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c311_ok : caseOKB c311 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c312_ok : caseOKB c312 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c313_ok : caseOKB c313 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c314_ok : caseOKB c314 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c315_ok : caseOKB c315 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c316_ok : caseOKB c316 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c317_ok : caseOKB c317 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c318_ok : caseOKB c318 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c319_ok : caseOKB c319 = true := by decide +kernel

end SB.Rooted.M5.Data
