/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 2: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c244_ok : caseOKB c244 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c245_ok : caseOKB c245 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c246_ok : caseOKB c246 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c247_ok : caseOKB c247 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c248_ok : caseOKB c248 = true := by decide +kernel

end SB.Rooted.M5.Data
