/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 03, part 6: one `decide +kernel` per case. -/
import RootedM5.Data.D03
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c252_ok : caseOKB c252 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c253_ok : caseOKB c253 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c254_ok : caseOKB c254 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c255_ok : caseOKB c255 = true := by decide +kernel

end SB.Rooted.M5.Data
