/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 04: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K04_00..K04_14. -/
import RootedM5.Checks.K04_00
import RootedM5.Checks.K04_01
import RootedM5.Checks.K04_02
import RootedM5.Checks.K04_03
import RootedM5.Checks.K04_04
import RootedM5.Checks.K04_05
import RootedM5.Checks.K04_06
import RootedM5.Checks.K04_07
import RootedM5.Checks.K04_08
import RootedM5.Checks.K04_09
import RootedM5.Checks.K04_10
import RootedM5.Checks.K04_11
import RootedM5.Checks.K04_12
import RootedM5.Checks.K04_13
import RootedM5.Checks.K04_14

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases04_ok : cases04.all caseOKB = true := by
  simp only [cases04, List.all_cons, List.all_nil, c320_ok, c321_ok, c322_ok, c323_ok, c324_ok, c325_ok, c326_ok, c327_ok, c328_ok, c329_ok, c330_ok, c331_ok, c332_ok, c333_ok, c334_ok, c335_ok, c336_ok, c337_ok, c338_ok, c339_ok, c340_ok, c341_ok, c342_ok, c343_ok, c344_ok, c345_ok, c346_ok, c347_ok, c348_ok, c349_ok, c350_ok, c351_ok, c352_ok, c353_ok, c354_ok, c355_ok, c356_ok, c357_ok, c358_ok, c359_ok, c360_ok, c361_ok, c362_ok, c363_ok, c364_ok, c365_ok, c366_ok, c367_ok, c368_ok, c369_ok, c370_ok, c371_ok, c372_ok, c373_ok, c374_ok, c375_ok, c376_ok, c377_ok, c378_ok, c379_ok, c380_ok, c381_ok, c382_ok, c383_ok, c384_ok, c385_ok, c386_ok, c387_ok, c388_ok, c389_ok, c390_ok, c391_ok, c392_ok, c393_ok, c394_ok, c395_ok, c396_ok, c397_ok, c398_ok, c399_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases04_ok
