/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 11: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c376_ok : caseOKB c376 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c377_ok : caseOKB c377 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c378_ok : caseOKB c378 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c379_ok : caseOKB c379 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c380_ok : caseOKB c380 = true := by decide +kernel

end SB.Rooted.M5.Data
