/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 13: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c382_ok : caseOKB c382 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c383_ok : caseOKB c383 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c384_ok : caseOKB c384 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c385_ok : caseOKB c385 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c386_ok : caseOKB c386 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c387_ok : caseOKB c387 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c388_ok : caseOKB c388 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c389_ok : caseOKB c389 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c390_ok : caseOKB c390 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c391_ok : caseOKB c391 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c392_ok : caseOKB c392 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c393_ok : caseOKB c393 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c394_ok : caseOKB c394 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c395_ok : caseOKB c395 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c396_ok : caseOKB c396 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c397_ok : caseOKB c397 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c398_ok : caseOKB c398 = true := by decide +kernel

end SB.Rooted.M5.Data
