/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 8: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c369_ok : caseOKB c369 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c370_ok : caseOKB c370 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c371_ok : caseOKB c371 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c372_ok : caseOKB c372 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c373_ok : caseOKB c373 = true := by decide +kernel

end SB.Rooted.M5.Data
