/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c320_ok : caseOKB c320 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c321_ok : caseOKB c321 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c322_ok : caseOKB c322 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c323_ok : caseOKB c323 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c324_ok : caseOKB c324 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c325_ok : caseOKB c325 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c326_ok : caseOKB c326 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c327_ok : caseOKB c327 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c328_ok : caseOKB c328 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c329_ok : caseOKB c329 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c330_ok : caseOKB c330 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c331_ok : caseOKB c331 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c332_ok : caseOKB c332 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c333_ok : caseOKB c333 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c334_ok : caseOKB c334 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c335_ok : caseOKB c335 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c336_ok : caseOKB c336 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c337_ok : caseOKB c337 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c338_ok : caseOKB c338 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c339_ok : caseOKB c339 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c340_ok : caseOKB c340 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c341_ok : caseOKB c341 = true := by decide +kernel

end SB.Rooted.M5.Data
