/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 7: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c353_ok : caseOKB c353 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c354_ok : caseOKB c354 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c355_ok : caseOKB c355 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c356_ok : caseOKB c356 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c357_ok : caseOKB c357 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c358_ok : caseOKB c358 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c359_ok : caseOKB c359 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c360_ok : caseOKB c360 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c361_ok : caseOKB c361 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c362_ok : caseOKB c362 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c363_ok : caseOKB c363 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c364_ok : caseOKB c364 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c365_ok : caseOKB c365 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c366_ok : caseOKB c366 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c367_ok : caseOKB c367 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c368_ok : caseOKB c368 = true := by decide +kernel

end SB.Rooted.M5.Data
