/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c342_ok : caseOKB c342 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c343_ok : caseOKB c343 = true := by decide +kernel

end SB.Rooted.M5.Data
