/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 04, part 4: one `decide +kernel` per case. -/
import RootedM5.Data.D04
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c346_ok : caseOKB c346 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c347_ok : caseOKB c347 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c348_ok : caseOKB c348 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c349_ok : caseOKB c349 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c350_ok : caseOKB c350 = true := by decide +kernel

end SB.Rooted.M5.Data
