/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 05: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K05_00..K05_07. -/
import RootedM5.Checks.K05_00
import RootedM5.Checks.K05_01
import RootedM5.Checks.K05_02
import RootedM5.Checks.K05_03
import RootedM5.Checks.K05_04
import RootedM5.Checks.K05_05
import RootedM5.Checks.K05_06
import RootedM5.Checks.K05_07

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases05_ok : cases05.all caseOKB = true := by
  simp only [cases05, List.all_cons, List.all_nil, c400_ok, c401_ok, c402_ok, c403_ok, c404_ok, c405_ok, c406_ok, c407_ok, c408_ok, c409_ok, c410_ok, c411_ok, c412_ok, c413_ok, c414_ok, c415_ok, c416_ok, c417_ok, c418_ok, c419_ok, c420_ok, c421_ok, c422_ok, c423_ok, c424_ok, c425_ok, c426_ok, c427_ok, c428_ok, c429_ok, c430_ok, c431_ok, c432_ok, c433_ok, c434_ok, c435_ok, c436_ok, c437_ok, c438_ok, c439_ok, c440_ok, c441_ok, c442_ok, c443_ok, c444_ok, c445_ok, c446_ok, c447_ok, c448_ok, c449_ok, c450_ok, c451_ok, c452_ok, c453_ok, c454_ok, c455_ok, c456_ok, c457_ok, c458_ok, c459_ok, c460_ok, c461_ok, c462_ok, c463_ok, c464_ok, c465_ok, c466_ok, c467_ok, c468_ok, c469_ok, c470_ok, c471_ok, c472_ok, c473_ok, c474_ok, c475_ok, c476_ok, c477_ok, c478_ok, c479_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases05_ok
