/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 05, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D05
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c400_ok : caseOKB c400 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c401_ok : caseOKB c401 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c402_ok : caseOKB c402 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c403_ok : caseOKB c403 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c404_ok : caseOKB c404 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c405_ok : caseOKB c405 = true := by decide +kernel

end SB.Rooted.M5.Data
