/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 05, part 6: one `decide +kernel` per case. -/
import RootedM5.Data.D05
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c446_ok : caseOKB c446 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c447_ok : caseOKB c447 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c448_ok : caseOKB c448 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c449_ok : caseOKB c449 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c450_ok : caseOKB c450 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c451_ok : caseOKB c451 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c452_ok : caseOKB c452 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c453_ok : caseOKB c453 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c454_ok : caseOKB c454 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c455_ok : caseOKB c455 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c456_ok : caseOKB c456 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c457_ok : caseOKB c457 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c458_ok : caseOKB c458 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c459_ok : caseOKB c459 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c460_ok : caseOKB c460 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c461_ok : caseOKB c461 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c462_ok : caseOKB c462 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c463_ok : caseOKB c463 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c464_ok : caseOKB c464 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c465_ok : caseOKB c465 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c466_ok : caseOKB c466 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c467_ok : caseOKB c467 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c468_ok : caseOKB c468 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c469_ok : caseOKB c469 = true := by decide +kernel

end SB.Rooted.M5.Data
