/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 05, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D05
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c406_ok : caseOKB c406 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c407_ok : caseOKB c407 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c408_ok : caseOKB c408 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c409_ok : caseOKB c409 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c410_ok : caseOKB c410 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c411_ok : caseOKB c411 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c412_ok : caseOKB c412 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c413_ok : caseOKB c413 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c414_ok : caseOKB c414 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c415_ok : caseOKB c415 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c416_ok : caseOKB c416 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c417_ok : caseOKB c417 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c418_ok : caseOKB c418 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c419_ok : caseOKB c419 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c420_ok : caseOKB c420 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c421_ok : caseOKB c421 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c422_ok : caseOKB c422 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c423_ok : caseOKB c423 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c424_ok : caseOKB c424 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c425_ok : caseOKB c425 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c426_ok : caseOKB c426 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c427_ok : caseOKB c427 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c428_ok : caseOKB c428 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c429_ok : caseOKB c429 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c430_ok : caseOKB c430 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c431_ok : caseOKB c431 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c432_ok : caseOKB c432 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c433_ok : caseOKB c433 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c434_ok : caseOKB c434 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c435_ok : caseOKB c435 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c436_ok : caseOKB c436 = true := by decide +kernel

end SB.Rooted.M5.Data
