/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 05, part 7: one `decide +kernel` per case. -/
import RootedM5.Data.D05
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c470_ok : caseOKB c470 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c471_ok : caseOKB c471 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c472_ok : caseOKB c472 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c473_ok : caseOKB c473 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c474_ok : caseOKB c474 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c475_ok : caseOKB c475 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c476_ok : caseOKB c476 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c477_ok : caseOKB c477 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c478_ok : caseOKB c478 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c479_ok : caseOKB c479 = true := by decide +kernel

end SB.Rooted.M5.Data
