/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 05, part 4: one `decide +kernel` per case. -/
import RootedM5.Data.D05
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c439_ok : caseOKB c439 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c440_ok : caseOKB c440 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c441_ok : caseOKB c441 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c442_ok : caseOKB c442 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c443_ok : caseOKB c443 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c444_ok : caseOKB c444 = true := by decide +kernel

end SB.Rooted.M5.Data
