/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 06: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K06_00..K06_01. -/
import RootedM5.Checks.K06_00
import RootedM5.Checks.K06_01

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases06_ok : cases06.all caseOKB = true := by
  simp only [cases06, List.all_cons, List.all_nil, c480_ok, c481_ok, c482_ok, c483_ok, c484_ok, c485_ok, c486_ok, c487_ok, c488_ok, c489_ok, c490_ok, c491_ok, c492_ok, c493_ok, c494_ok, c495_ok, c496_ok, c497_ok, c498_ok, c499_ok, c500_ok, c501_ok, c502_ok, c503_ok, c504_ok, c505_ok, c506_ok, c507_ok, c508_ok, c509_ok, c510_ok, c511_ok, c512_ok, c513_ok, c514_ok, c515_ok, c516_ok, c517_ok, c518_ok, c519_ok, c520_ok, c521_ok, c522_ok, c523_ok, c524_ok, c525_ok, c526_ok, c527_ok, c528_ok, c529_ok, c530_ok, c531_ok, c532_ok, c533_ok, c534_ok, c535_ok, c536_ok, c537_ok, c538_ok, c539_ok, c540_ok, c541_ok, c542_ok, c543_ok, c544_ok, c545_ok, c546_ok, c547_ok, c548_ok, c549_ok, c550_ok, c551_ok, c552_ok, c553_ok, c554_ok, c555_ok, c556_ok, c557_ok, c558_ok, c559_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases06_ok
