/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 06, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D06
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c539_ok : caseOKB c539 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c540_ok : caseOKB c540 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c541_ok : caseOKB c541 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c542_ok : caseOKB c542 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c543_ok : caseOKB c543 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c544_ok : caseOKB c544 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c545_ok : caseOKB c545 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c546_ok : caseOKB c546 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c547_ok : caseOKB c547 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c548_ok : caseOKB c548 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c549_ok : caseOKB c549 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c550_ok : caseOKB c550 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c551_ok : caseOKB c551 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c552_ok : caseOKB c552 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c553_ok : caseOKB c553 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c554_ok : caseOKB c554 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c555_ok : caseOKB c555 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c556_ok : caseOKB c556 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c557_ok : caseOKB c557 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c558_ok : caseOKB c558 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c559_ok : caseOKB c559 = true := by decide +kernel

end SB.Rooted.M5.Data
