/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 06, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D06
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c480_ok : caseOKB c480 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c481_ok : caseOKB c481 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c482_ok : caseOKB c482 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c483_ok : caseOKB c483 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c484_ok : caseOKB c484 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c485_ok : caseOKB c485 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c486_ok : caseOKB c486 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c487_ok : caseOKB c487 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c488_ok : caseOKB c488 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c489_ok : caseOKB c489 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c490_ok : caseOKB c490 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c491_ok : caseOKB c491 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c492_ok : caseOKB c492 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c493_ok : caseOKB c493 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c494_ok : caseOKB c494 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c495_ok : caseOKB c495 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c496_ok : caseOKB c496 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c497_ok : caseOKB c497 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c498_ok : caseOKB c498 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c499_ok : caseOKB c499 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c500_ok : caseOKB c500 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c501_ok : caseOKB c501 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c502_ok : caseOKB c502 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c503_ok : caseOKB c503 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c504_ok : caseOKB c504 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c505_ok : caseOKB c505 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c506_ok : caseOKB c506 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c507_ok : caseOKB c507 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c508_ok : caseOKB c508 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c509_ok : caseOKB c509 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c510_ok : caseOKB c510 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c511_ok : caseOKB c511 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c512_ok : caseOKB c512 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c513_ok : caseOKB c513 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c514_ok : caseOKB c514 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c515_ok : caseOKB c515 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c516_ok : caseOKB c516 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c517_ok : caseOKB c517 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c518_ok : caseOKB c518 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c519_ok : caseOKB c519 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c520_ok : caseOKB c520 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c521_ok : caseOKB c521 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c522_ok : caseOKB c522 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c523_ok : caseOKB c523 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c524_ok : caseOKB c524 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c525_ok : caseOKB c525 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c526_ok : caseOKB c526 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c527_ok : caseOKB c527 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c528_ok : caseOKB c528 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c529_ok : caseOKB c529 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c530_ok : caseOKB c530 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c531_ok : caseOKB c531 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c532_ok : caseOKB c532 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c533_ok : caseOKB c533 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c534_ok : caseOKB c534 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c535_ok : caseOKB c535 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c536_ok : caseOKB c536 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c537_ok : caseOKB c537 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c538_ok : caseOKB c538 = true := by decide +kernel

end SB.Rooted.M5.Data
