/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 07: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K07_00..K07_01. -/
import RootedM5.Checks.K07_00
import RootedM5.Checks.K07_01

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases07_ok : cases07.all caseOKB = true := by
  simp only [cases07, List.all_cons, List.all_nil, c560_ok, c561_ok, c562_ok, c563_ok, c564_ok, c565_ok, c566_ok, c567_ok, c568_ok, c569_ok, c570_ok, c571_ok, c572_ok, c573_ok, c574_ok, c575_ok, c576_ok, c577_ok, c578_ok, c579_ok, c580_ok, c581_ok, c582_ok, c583_ok, c584_ok, c585_ok, c586_ok, c587_ok, c588_ok, c589_ok, c590_ok, c591_ok, c592_ok, c593_ok, c594_ok, c595_ok, c596_ok, c597_ok, c598_ok, c599_ok, c600_ok, c601_ok, c602_ok, c603_ok, c604_ok, c605_ok, c606_ok, c607_ok, c608_ok, c609_ok, c610_ok, c611_ok, c612_ok, c613_ok, c614_ok, c615_ok, c616_ok, c617_ok, c618_ok, c619_ok, c620_ok, c621_ok, c622_ok, c623_ok, c624_ok, c625_ok, c626_ok, c627_ok, c628_ok, c629_ok, c630_ok, c631_ok, c632_ok, c633_ok, c634_ok, c635_ok, c636_ok, c637_ok, c638_ok, c639_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases07_ok
