/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 07, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D07
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c617_ok : caseOKB c617 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c618_ok : caseOKB c618 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c619_ok : caseOKB c619 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c620_ok : caseOKB c620 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c621_ok : caseOKB c621 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c622_ok : caseOKB c622 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c623_ok : caseOKB c623 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c624_ok : caseOKB c624 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c625_ok : caseOKB c625 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c626_ok : caseOKB c626 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c627_ok : caseOKB c627 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c628_ok : caseOKB c628 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c629_ok : caseOKB c629 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c630_ok : caseOKB c630 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c631_ok : caseOKB c631 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c632_ok : caseOKB c632 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c633_ok : caseOKB c633 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c634_ok : caseOKB c634 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c635_ok : caseOKB c635 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c636_ok : caseOKB c636 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c637_ok : caseOKB c637 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c638_ok : caseOKB c638 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c639_ok : caseOKB c639 = true := by decide +kernel

end SB.Rooted.M5.Data
