/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 07, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D07
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c560_ok : caseOKB c560 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c561_ok : caseOKB c561 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c562_ok : caseOKB c562 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c563_ok : caseOKB c563 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c564_ok : caseOKB c564 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c565_ok : caseOKB c565 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c566_ok : caseOKB c566 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c567_ok : caseOKB c567 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c568_ok : caseOKB c568 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c569_ok : caseOKB c569 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c570_ok : caseOKB c570 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c571_ok : caseOKB c571 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c572_ok : caseOKB c572 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c573_ok : caseOKB c573 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c574_ok : caseOKB c574 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c575_ok : caseOKB c575 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c576_ok : caseOKB c576 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c577_ok : caseOKB c577 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c578_ok : caseOKB c578 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c579_ok : caseOKB c579 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c580_ok : caseOKB c580 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c581_ok : caseOKB c581 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c582_ok : caseOKB c582 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c583_ok : caseOKB c583 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c584_ok : caseOKB c584 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c585_ok : caseOKB c585 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c586_ok : caseOKB c586 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c587_ok : caseOKB c587 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c588_ok : caseOKB c588 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c589_ok : caseOKB c589 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c590_ok : caseOKB c590 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c591_ok : caseOKB c591 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c592_ok : caseOKB c592 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c593_ok : caseOKB c593 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c594_ok : caseOKB c594 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c595_ok : caseOKB c595 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c596_ok : caseOKB c596 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c597_ok : caseOKB c597 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c598_ok : caseOKB c598 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c599_ok : caseOKB c599 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c600_ok : caseOKB c600 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c601_ok : caseOKB c601 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c602_ok : caseOKB c602 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c603_ok : caseOKB c603 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c604_ok : caseOKB c604 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c605_ok : caseOKB c605 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c606_ok : caseOKB c606 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c607_ok : caseOKB c607 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c608_ok : caseOKB c608 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c609_ok : caseOKB c609 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c610_ok : caseOKB c610 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c611_ok : caseOKB c611 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c612_ok : caseOKB c612 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c613_ok : caseOKB c613 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c614_ok : caseOKB c614 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c615_ok : caseOKB c615 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c616_ok : caseOKB c616 = true := by decide +kernel

end SB.Rooted.M5.Data
