/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 08: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K08_00..K08_01. -/
import RootedM5.Checks.K08_00
import RootedM5.Checks.K08_01

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases08_ok : cases08.all caseOKB = true := by
  simp only [cases08, List.all_cons, List.all_nil, c640_ok, c641_ok, c642_ok, c643_ok, c644_ok, c645_ok, c646_ok, c647_ok, c648_ok, c649_ok, c650_ok, c651_ok, c652_ok, c653_ok, c654_ok, c655_ok, c656_ok, c657_ok, c658_ok, c659_ok, c660_ok, c661_ok, c662_ok, c663_ok, c664_ok, c665_ok, c666_ok, c667_ok, c668_ok, c669_ok, c670_ok, c671_ok, c672_ok, c673_ok, c674_ok, c675_ok, c676_ok, c677_ok, c678_ok, c679_ok, c680_ok, c681_ok, c682_ok, c683_ok, c684_ok, c685_ok, c686_ok, c687_ok, c688_ok, c689_ok, c690_ok, c691_ok, c692_ok, c693_ok, c694_ok, c695_ok, c696_ok, c697_ok, c698_ok, c699_ok, c700_ok, c701_ok, c702_ok, c703_ok, c704_ok, c705_ok, c706_ok, c707_ok, c708_ok, c709_ok, c710_ok, c711_ok, c712_ok, c713_ok, c714_ok, c715_ok, c716_ok, c717_ok, c718_ok, c719_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases08_ok
