/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 08, part 1: one `decide +kernel` per case. -/
import RootedM5.Data.D08
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c717_ok : caseOKB c717 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c718_ok : caseOKB c718 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c719_ok : caseOKB c719 = true := by decide +kernel

end SB.Rooted.M5.Data
