/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 08, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D08
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c640_ok : caseOKB c640 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c641_ok : caseOKB c641 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c642_ok : caseOKB c642 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c643_ok : caseOKB c643 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c644_ok : caseOKB c644 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c645_ok : caseOKB c645 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c646_ok : caseOKB c646 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c647_ok : caseOKB c647 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c648_ok : caseOKB c648 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c649_ok : caseOKB c649 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c650_ok : caseOKB c650 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c651_ok : caseOKB c651 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c652_ok : caseOKB c652 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c653_ok : caseOKB c653 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c654_ok : caseOKB c654 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c655_ok : caseOKB c655 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c656_ok : caseOKB c656 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c657_ok : caseOKB c657 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c658_ok : caseOKB c658 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c659_ok : caseOKB c659 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c660_ok : caseOKB c660 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c661_ok : caseOKB c661 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c662_ok : caseOKB c662 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c663_ok : caseOKB c663 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c664_ok : caseOKB c664 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c665_ok : caseOKB c665 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c666_ok : caseOKB c666 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c667_ok : caseOKB c667 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c668_ok : caseOKB c668 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c669_ok : caseOKB c669 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c670_ok : caseOKB c670 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c671_ok : caseOKB c671 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c672_ok : caseOKB c672 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c673_ok : caseOKB c673 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c674_ok : caseOKB c674 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c675_ok : caseOKB c675 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c676_ok : caseOKB c676 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c677_ok : caseOKB c677 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c678_ok : caseOKB c678 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c679_ok : caseOKB c679 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c680_ok : caseOKB c680 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c681_ok : caseOKB c681 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c682_ok : caseOKB c682 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c683_ok : caseOKB c683 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c684_ok : caseOKB c684 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c685_ok : caseOKB c685 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c686_ok : caseOKB c686 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c687_ok : caseOKB c687 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c688_ok : caseOKB c688 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c689_ok : caseOKB c689 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c690_ok : caseOKB c690 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c691_ok : caseOKB c691 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c692_ok : caseOKB c692 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c693_ok : caseOKB c693 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c694_ok : caseOKB c694 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c695_ok : caseOKB c695 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c696_ok : caseOKB c696 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c697_ok : caseOKB c697 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c698_ok : caseOKB c698 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c699_ok : caseOKB c699 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c700_ok : caseOKB c700 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c701_ok : caseOKB c701 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c702_ok : caseOKB c702 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c703_ok : caseOKB c703 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c704_ok : caseOKB c704 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c705_ok : caseOKB c705 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c706_ok : caseOKB c706 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c707_ok : caseOKB c707 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c708_ok : caseOKB c708 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c709_ok : caseOKB c709 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c710_ok : caseOKB c710 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c711_ok : caseOKB c711 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c712_ok : caseOKB c712 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c713_ok : caseOKB c713 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c714_ok : caseOKB c714 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c715_ok : caseOKB c715 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c716_ok : caseOKB c716 = true := by decide +kernel

end SB.Rooted.M5.Data
