/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel check of data chunk 09: every case is a census case, its entries are the listed words of
   its family in certificate order (`H = wordEdges k w`), and every split verdict is a complete split.
   The per-case checks are in K09_00..K09_00. -/
import RootedM5.Checks.K09_00

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

theorem cases09_ok : cases09.all caseOKB = true := by
  simp only [cases09, List.all_cons, List.all_nil, c720_ok, c721_ok, c722_ok, c723_ok, c724_ok, c725_ok, c726_ok, c727_ok, c728_ok, c729_ok, c730_ok, c731_ok, c732_ok, c733_ok, c734_ok, c735_ok, c736_ok, c737_ok, c738_ok, c739_ok, c740_ok, c741_ok, c742_ok, c743_ok, c744_ok, c745_ok, c746_ok, c747_ok, c748_ok, c749_ok, c750_ok, c751_ok, c752_ok, c753_ok, c754_ok, c755_ok, c756_ok, c757_ok, c758_ok, c759_ok, c760_ok, c761_ok, c762_ok, c763_ok, c764_ok, c765_ok, c766_ok, c767_ok, c768_ok, c769_ok, c770_ok, c771_ok, c772_ok, c773_ok, c774_ok, c775_ok, c776_ok, c777_ok, c778_ok, c779_ok, c780_ok, Bool.and_self]

end SB.Rooted.M5.Data

#print axioms SB.Rooted.M5.Data.cases09_ok
