/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit.
   Kernel checks of data chunk 09, part 0: one `decide +kernel` per case. -/
import RootedM5.Data.D09
import RootedM5.CheckDefs

namespace SB.Rooted.M5.Data
open SB.Rooted.M5

set_option maxRecDepth 100000 in
theorem c720_ok : caseOKB c720 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c721_ok : caseOKB c721 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c722_ok : caseOKB c722 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c723_ok : caseOKB c723 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c724_ok : caseOKB c724 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c725_ok : caseOKB c725 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c726_ok : caseOKB c726 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c727_ok : caseOKB c727 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c728_ok : caseOKB c728 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c729_ok : caseOKB c729 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c730_ok : caseOKB c730 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c731_ok : caseOKB c731 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c732_ok : caseOKB c732 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c733_ok : caseOKB c733 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c734_ok : caseOKB c734 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c735_ok : caseOKB c735 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c736_ok : caseOKB c736 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c737_ok : caseOKB c737 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c738_ok : caseOKB c738 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c739_ok : caseOKB c739 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c740_ok : caseOKB c740 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c741_ok : caseOKB c741 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c742_ok : caseOKB c742 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c743_ok : caseOKB c743 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c744_ok : caseOKB c744 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c745_ok : caseOKB c745 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c746_ok : caseOKB c746 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c747_ok : caseOKB c747 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c748_ok : caseOKB c748 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c749_ok : caseOKB c749 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c750_ok : caseOKB c750 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c751_ok : caseOKB c751 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c752_ok : caseOKB c752 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c753_ok : caseOKB c753 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c754_ok : caseOKB c754 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c755_ok : caseOKB c755 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c756_ok : caseOKB c756 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c757_ok : caseOKB c757 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c758_ok : caseOKB c758 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c759_ok : caseOKB c759 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c760_ok : caseOKB c760 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c761_ok : caseOKB c761 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c762_ok : caseOKB c762 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c763_ok : caseOKB c763 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c764_ok : caseOKB c764 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c765_ok : caseOKB c765 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c766_ok : caseOKB c766 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c767_ok : caseOKB c767 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c768_ok : caseOKB c768 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c769_ok : caseOKB c769 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c770_ok : caseOKB c770 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c771_ok : caseOKB c771 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c772_ok : caseOKB c772 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c773_ok : caseOKB c773 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c774_ok : caseOKB c774 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c775_ok : caseOKB c775 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c776_ok : caseOKB c776 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c777_ok : caseOKB c777 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c778_ok : caseOKB c778 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c779_ok : caseOKB c779 = true := by decide +kernel
set_option maxRecDepth 100000 in
theorem c780_ok : caseOKB c780 = true := by decide +kernel

end SB.Rooted.M5.Data
