/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k10_c019, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k10_c019
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

theorem k10_c019_ck0 : chunkLW 10 k10_c019_b0 = [] := by decide +kernel
def LW_k10_c019 : List (List (Nat × Nat)) := ([])
theorem famLW_k10_c019 : (listedWords k10_c019).map (wordEdges 10) = LW_k10_c019 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 10 0 1 9
    (k10_c019_p0)
    (k10_c019_b0))).map (wordEdges 10) = LW_k10_c019
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k10_c019_ck0]
  rfl

end SB.Rooted.M5.Fam
