/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c224, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c224
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

def k8_c224_lw0 : List (List (Nat × Nat)) := [[(2, 9), (3, 9), (4, 7), (4, 8), (5, 6), (5, 8), (6, 7), (8, 9)], [(2, 9), (3, 9), (4, 7), (4, 8), (5, 6), (5, 8), (6, 7), (6, 9), (7, 8)], [(2, 9), (3, 8), (4, 8), (4, 9), (5, 7), (5, 9), (6, 7), (6, 8)], [(2, 9), (3, 8), (4, 8), (4, 9), (5, 6), (5, 7), (6, 7), (6, 9), (7, 8)]]
theorem k8_c224_ck0 : chunkLW 8 k8_c224_b0 = k8_c224_lw0 := by decide +kernel
def k8_c224_lw1 : List (List (Nat × Nat)) := [[(2, 9), (3, 8), (4, 7), (4, 9), (5, 7), (5, 8), (6, 8), (6, 9)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 9), (6, 7), (6, 8), (7, 8)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 8), (6, 9), (7, 8)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 8), (6, 7), (8, 9)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 8), (6, 7), (6, 8), (7, 9)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 7), (6, 8), (6, 9), (7, 8)], [(2, 9), (3, 8), (4, 7), (4, 9), (5, 6), (5, 7), (6, 7), (6, 8), (8, 9)], [(2, 9), (3, 8), (4, 6), (4, 7), (5, 6), (5, 7), (6, 9), (7, 8), (8, 9)], [(2, 9), (3, 8), (4, 5), (4, 9), (5, 7), (6, 7), (6, 8), (6, 9), (7, 8)], [(2, 9), (3, 8), (4, 5), (4, 7), (5, 7), (6, 7), (6, 8), (6, 9), (8, 9)], [(2, 9), (3, 8), (4, 5), (4, 7), (5, 6), (6, 8), (6, 9), (7, 8), (7, 9)], [(2, 9), (3, 5), (4, 8), (4, 9), (5, 7), (6, 7), (6, 8), (6, 9), (7, 8)], [(2, 9), (3, 5), (4, 7), (4, 8), (5, 8), (6, 7), (6, 8), (6, 9), (7, 9)], [(2, 9), (3, 5), (4, 7), (4, 8), (5, 6), (6, 8), (6, 9), (7, 8), (7, 9)]]
theorem k8_c224_ck1 : chunkLW 8 k8_c224_b1 = k8_c224_lw1 := by decide +kernel
theorem k8_c224_ck2 : chunkLW 8 k8_c224_b2 = [] := by decide +kernel
def LW_k8_c224 : List (List (Nat × Nat)) := k8_c224_lw0 ++ k8_c224_lw1 ++ ([])
theorem famLW_k8_c224 : (listedWords k8_c224).map (wordEdges 8) = LW_k8_c224 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 2 2 4
    (k8_c224_p0)
    (k8_c224_b0 ++ k8_c224_b1 ++ k8_c224_b2))).map (wordEdges 8) = LW_k8_c224
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c224_ck0, k8_c224_ck1, k8_c224_ck2]
  rfl

end SB.Rooted.M5.Fam
