/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c215, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c215
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

theorem k8_c215_ck0 : chunkLW 8 k8_c215_b0 = [] := by decide +kernel
def LW_k8_c215 : List (List (Nat × Nat)) := ([])
theorem famLW_k8_c215 : (listedWords k8_c215).map (wordEdges 8) = LW_k8_c215 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 2 1 5
    (k8_c215_p0)
    (k8_c215_b0))).map (wordEdges 8) = LW_k8_c215
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c215_ck0]
  rfl

end SB.Rooted.M5.Fam
