/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c080, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c080
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

def k8_c080_lw0 : List (List (Nat × Nat)) := [[(2, 8), (2, 9), (3, 7), (3, 9), (4, 6), (4, 8), (5, 6), (5, 7)]]
theorem k8_c080_ck0 : chunkLW 8 k8_c080_b0 = k8_c080_lw0 := by decide +kernel
def LW_k8_c080 : List (List (Nat × Nat)) := k8_c080_lw0
theorem famLW_k8_c080 : (listedWords k8_c080).map (wordEdges 8) = LW_k8_c080 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 0 8 0
    (k8_c080_p0)
    (k8_c080_b0))).map (wordEdges 8) = LW_k8_c080
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c080_ck0]
  rfl

end SB.Rooted.M5.Fam
