/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c026, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c026
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

theorem k8_c026_ck0 : chunkLW 8 k8_c026_b0 = [] := by decide +kernel
theorem k8_c026_ck1 : chunkLW 8 k8_c026_b1 = [] := by decide +kernel
def LW_k8_c026 : List (List (Nat × Nat)) := ([]) ++ ([])
theorem famLW_k8_c026 : (listedWords k8_c026).map (wordEdges 8) = LW_k8_c026 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 0 2 6
    (k8_c026_p0)
    (k8_c026_b0 ++ k8_c026_b1))).map (wordEdges 8) = LW_k8_c026
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c026_ck0, k8_c026_ck1]
  rfl

end SB.Rooted.M5.Fam
