/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c413, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c413
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

def k8_c413_lw0 : List (List (Nat × Nat)) := [[(3, 9), (4, 9), (5, 8), (6, 7), (6, 8), (7, 8), (7, 9)], [(3, 9), (4, 8), (5, 7), (6, 8), (6, 9), (7, 8), (7, 9)], [(3, 9), (4, 8), (5, 6), (6, 7), (7, 8), (7, 9), (8, 9)], [(2, 9), (3, 9), (4, 9), (5, 8), (6, 7), (6, 8), (7, 8)], [(2, 9), (3, 9), (4, 8), (5, 8), (6, 7), (7, 8), (7, 9)], [(2, 9), (3, 9), (4, 8), (5, 8), (6, 7), (6, 9), (7, 8)], [(2, 9), (3, 9), (4, 8), (5, 7), (6, 8), (7, 8), (7, 9)], [(2, 9), (3, 9), (4, 8), (5, 7), (6, 8), (6, 9), (7, 8)], [(2, 9), (3, 9), (4, 8), (5, 7), (6, 7), (6, 8), (8, 9)], [(2, 9), (3, 9), (4, 8), (5, 7), (6, 7), (6, 8), (7, 8)], [(2, 9), (3, 9), (4, 8), (5, 6), (6, 8), (7, 8), (7, 9)], [(2, 9), (3, 9), (4, 8), (5, 6), (6, 7), (7, 8), (8, 9)], [(2, 9), (3, 9), (4, 8), (5, 6), (6, 7), (7, 8), (7, 9)], [(2, 9), (3, 9), (4, 5), (6, 7), (6, 8), (7, 8), (8, 9)], [(2, 9), (3, 8), (4, 7), (5, 6), (7, 8), (7, 9), (8, 9)], [(2, 9), (3, 8), (4, 7), (5, 6), (6, 9), (7, 8), (8, 9)]]
theorem k8_c413_ck0 : chunkLW 8 k8_c413_b0 = k8_c413_lw0 := by decide +kernel
def LW_k8_c413 : List (List (Nat × Nat)) := k8_c413_lw0
theorem famLW_k8_c413 : (listedWords k8_c413).map (wordEdges 8) = LW_k8_c413 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 4 1 3
    (k8_c413_p0)
    (k8_c413_b0))).map (wordEdges 8) = LW_k8_c413
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c413_ck0]
  rfl

end SB.Rooted.M5.Fam
