/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   The listed words of the M0 certificate k8_c521, as `wordEdges` lists, chunk by chunk. -/
import RootedM4.CoverData.F_k8_c521
import RootedM5.FamDefs

namespace SB.Rooted.M5.Fam
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5

def k8_c521_lw0 : List (List (Nat × Nat)) := [[(4, 9), (5, 9), (6, 8), (7, 8), (7, 9)], [(4, 9), (5, 8), (6, 7), (7, 9), (8, 9)], [(4, 9), (5, 6), (7, 8), (7, 9), (8, 9)], [(3, 9), (4, 9), (5, 8), (6, 7), (8, 9)], [(3, 9), (4, 9), (5, 8), (6, 7), (7, 8)], [(3, 9), (4, 9), (5, 6), (7, 8), (8, 9)], [(3, 9), (4, 8), (5, 6), (7, 9), (8, 9)], [(3, 9), (4, 8), (5, 6), (7, 8), (7, 9)], [(3, 8), (4, 7), (5, 6), (7, 9), (8, 9)], [(2, 9), (3, 9), (4, 9), (5, 8), (6, 7)], [(2, 9), (3, 9), (4, 9), (5, 8), (6, 7), (7, 8)], [(2, 9), (3, 9), (4, 9), (5, 6), (7, 8)], [(2, 9), (3, 9), (4, 8), (5, 6), (7, 9)], [(2, 9), (3, 9), (4, 8), (5, 6), (7, 8), (7, 9)], [(2, 9), (3, 8), (4, 7), (5, 6), (8, 9)], [(2, 9), (3, 8), (4, 7), (5, 6), (7, 9), (8, 9)], [(2, 9), (3, 6), (4, 5), (7, 8), (8, 9)], [(2, 9), (3, 6), (4, 5), (7, 8), (7, 9), (8, 9)], [(2, 8), (3, 6), (4, 5), (7, 9), (8, 9)]]
theorem k8_c521_ck0 : chunkLW 8 k8_c521_b0 = k8_c521_lw0 := by decide +kernel
def LW_k8_c521 : List (List (Nat × Nat)) := k8_c521_lw0
theorem famLW_k8_c521 : (listedWords k8_c521).map (wordEdges 8) = LW_k8_c521 := by
  show (listedWords (SB.Rooted.M4.Cover.rawCert 8 5 2 1
    (k8_c521_p0)
    (k8_c521_b0))).map (wordEdges 8) = LW_k8_c521
  rw [listedWords_rawCert]
  simp only [chunkLW_append, k8_c521_ck0]
  rfl

end SB.Rooted.M5.Fam
