/-
# `R(K_{3,5}, K_{2,4}) = 19`, Comparator-grade route: no `native_decide`

The same composition as `FaithfulK35K25Comparator.lean`, for the cell `k35k24_n19`:
* `LRATCatcher.Comparator.K35K24.encoded_unsat` (module `LRATCatcher.ComparatorUnsatK35K24`): the Lean encoder's own
  output `toCNF (encodeBip 19 3 5 2 4)` is unsatisfiable, through two named axioms, `leaves_cakelpr`
  (773 leaf files) and `cover_cakelpr`, each discharged outside Lean by cake_lpr on DIMACS printed from the
  Lean terms;
* `SB.BipBridge.no_colouring_of_toCNFV_unsat` (`lean/sbsound`): unsatisfiability of the encoding refutes every
  good 2-colouring (encoding soundness and vertex-lex symmetry breaking; standard axioms only);
* `SB.Witness18b.witness_kernel` (`lean/sbsound`, generated by `gen_witness_kernel.py` from `k35k24-n19/witness/`): an
  explicit good colouring of `K_18`, checked by `decide +kernel`.
-/
import LRATCatcher.ComparatorUnsatK35K24
import Sbsound.BipBridge
import Sbsound.Witness18bKernel

namespace LRATCatcher.FaithfulK35K24

open SB

/-! The vendored copy of the encoder is the original. Every definition except `combos`
is identified by `rfl`; `combos` is structurally recursive and the elaborator's smart
unfolding does not compare two separately compiled copies, so it is identified by
recursion on its own equations, and the two definitions built on it follow by rewriting. -/

theorem combos_eq : ∀ (k : ℕ) (l : List ℕ),
    SB.Encoder.combos k l = LRATCatcher.Encoder.combos k l
  | 0, [] => rfl
  | 0, _ :: _ => rfl
  | _ + 1, [] => rfl
  | k + 1, x :: xs => by
    simp only [SB.Encoder.combos, LRATCatcher.Encoder.combos]
    rw [combos_eq k xs, combos_eq (k + 1) xs]

theorem combos_eq' : SB.Encoder.combos = LRATCatcher.Encoder.combos := by
  funext k l; exact combos_eq k l

theorem codegreeColour_eq :
    SB.Encoder.codegreeColour = LRATCatcher.Encoder.codegreeColour := by
  funext n r c s t nv0
  unfold SB.Encoder.codegreeColour LRATCatcher.Encoder.codegreeColour
  rw [combos_eq']
  rfl

theorem encodeBip_eq (n s₀ t₀ s₁ t₁ : ℕ) :
    SB.Encoder.encodeBip n s₀ t₀ s₁ t₁ = LRATCatcher.Encoder.encodeBip n s₀ t₀ s₁ t₁ := by
  unfold SB.Encoder.encodeBip LRATCatcher.Encoder.encodeBip
  rw [codegreeColour_eq]
  rfl

/-- The vendored DIMACS conversion is `LRATCatcher.Encoder.toCNF`, definitionally
(both convert a literal by `l ↦ (|l| - 1, decide (0 < l))`). -/
theorem toCNF_eq (cs : List (List Int)) :
    SB.BipBridge.toCNFV cs = LRATCatcher.Encoder.toCNF cs := rfl

/-- The cake_lpr-certified `encoded_unsat`, restated on the vendored definitions. -/
theorem vendored_unsat : (SB.BipBridge.toCNFV (SB.Encoder.encodeBip 19 3 5 2 4)).Unsat := by
  rw [toCNF_eq, encodeBip_eq]
  exact LRATCatcher.Comparator.K35K24.encoded_unsat

/-- **No 2-colouring of `K_19` avoids `K_{3,5}` in colour 0 and `K_{2,4}` in colour 1.** -/
theorem no_good_colouring_K19 :
    ¬ ∃ a : EColouring 19 2, NoKst a 0 3 5 ∧ NoKst a 1 2 4 :=
  SB.BipBridge.no_colouring_of_toCNFV_unsat (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) vendored_unsat

/-- **`R(K_{3,5}, K_{2,4}) = 19`**: no good colouring of `K_19`, and an explicit good colouring of
`K_18`. -/
theorem k35k24_eq_19 :
    (¬ ∃ a : EColouring 19 2, NoKst a 0 3 5 ∧ NoKst a 1 2 4) ∧
    (∃ a : EColouring 18 2, NoKst a 0 3 5 ∧ NoKst a 1 2 4) :=
  ⟨no_good_colouring_K19,
   ⟨SB.Witness18b.w, SB.Witness18b.witness_kernel.1, SB.Witness18b.witness_kernel.2⟩⟩

end LRATCatcher.FaithfulK35K24

#print axioms LRATCatcher.FaithfulK35K24.no_good_colouring_K19
#print axioms LRATCatcher.FaithfulK35K24.k35k24_eq_19
