#!/usr/bin/env python3
"""M4: write the 53 M0 family certificates (m0_hcover/data/*/cert_*.json) as Lean terms.

One module per family, lean-sb/RootedM4/CoverData/F_<tag>.lean, defining
  SB.Rooted.M4.CoverData.<tag> : SB.Rooted.M4.Cover.FamCert
with the recorded permutations in certificate order and the blocked words in CNF order.
A word is stored as a bitmask (bit n = character n of the word) and a kind U (0 = listed,
U > 0 = filter-(iii) blocker with vertex bitmask U); `rawCert` decodes them. Long lists are
cut into chunks so that the elaborator never sees one huge list literal.
Also writes CoverData/All.lean (the list `allCerts` and the lookup `certOf`).
usage: gen_cover_data.py   (no arguments; deterministic output)"""
import json, glob, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
M0 = os.path.join(HERE, '..', 'm0_hcover', 'data')
OUT = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..', 'lean', 'sbsound', 'RootedM4', 'CoverData'))
CH = 400


def chunks(xs, n):
    return [xs[i:i + n] for i in range(0, len(xs), n)] or [[]]


def main():
    os.makedirs(OUT, exist_ok=True)
    tags = []
    for f in sorted(glob.glob(os.path.join(M0, '*', 'cert_*.json'))):
        c = json.load(open(f))
        fam = c['family']
        k, comp = fam['k'], fam['comp']
        tag = 'k%d_c%d%d%d' % (k, comp[0], comp[1], comp[2])
        assert os.path.basename(f) == f'cert_{tag}.json'
        perms = c['perms']
        bl = []
        for b in c['blockers']:
            w = b['word']
            m = sum(1 << n for n, ch in enumerate(w) if ch == '1')
            u = 0 if b['kind'] == 'listed' else b['U']
            assert b['kind'] in ('listed', 'filter_iii') and (u > 0) == (b['kind'] == 'filter_iii')
            bl.append((m, u))
        L = [f'/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py from m0_hcover/data/{tag}/cert_{tag}.json',
             f'   (cnf_sha256 {c["cnf_sha256"]}). Do not edit. -/',
             'import RootedM4.CoverBase', '', 'namespace SB.Rooted.M4.CoverData', '']
        pc = chunks(perms, CH)
        for i, ch in enumerate(pc):
            L.append(f'def {tag}_p{i} : List (List Nat) := [' + ', '.join('[' + ','.join(map(str, p)) + ']' for p in ch) + ']')
        bc = chunks(bl, CH)
        for i, ch in enumerate(bc):
            L.append(f'def {tag}_b{i} : List (Nat × Nat) := [' + ', '.join(f'({m},{u})' for m, u in ch) + ']')
        L.append('')
        L.append(f'def {tag} : SB.Rooted.M4.Cover.FamCert := SB.Rooted.M4.Cover.rawCert {k} {comp[0]} {comp[1]} {comp[2]}')
        L.append('  (' + ' ++ '.join(f'{tag}_p{i}' for i in range(len(pc))) + ')')
        L.append('  (' + ' ++ '.join(f'{tag}_b{i}' for i in range(len(bc))) + ')')
        L.append('')
        L.append('end SB.Rooted.M4.CoverData')
        open(os.path.join(OUT, f'F_{tag}.lean'), 'w').write('\n'.join(L) + '\n')
        tags.append((tag, k, comp))
    A = ['/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit. -/']
    A += [f'import RootedM4.CoverData.F_{t}' for t, _, _ in tags]
    A += ['', 'namespace SB.Rooted.M4.CoverData', '',
          '/-- The 53 M0 family certificates. -/',
          'def allCerts : List SB.Rooted.M4.Cover.FamCert := [' + ', '.join(t for t, _, _ in tags) + ']', '',
          '/-- Their keys `(k, v8, v9, v10)`, in the same order. -/',
          'def famKeys : List (Nat × Nat × Nat × Nat) := [' +
          ', '.join(f'({k}, {c[0]}, {c[1]}, {c[2]})' for _, k, c in tags) + ']', '',
          '/-- The certificate of family `(k, v8, v9, v10)`. -/',
          'def certOf (k v8 v9 v10 : Nat) : SB.Rooted.M4.Cover.FamCert :=',
          '  allCerts.getD (famKeys.idxOf (k, v8, v9, v10)) ' + tags[0][0],
          '', 'end SB.Rooted.M4.CoverData']
    open(os.path.join(OUT, 'All.lean'), 'w').write('\n'.join(A) + '\n')
    # kernel-check modules, one per family
    CK = os.path.join(os.path.dirname(OUT), 'CoverChecks')
    os.makedirs(CK, exist_ok=True)
    for tag, k, comp in tags:
        src = open(os.path.join(OUT, f'F_{tag}.lean')).read()
        npc = len(re.findall(rf'^def {tag}_p\d+ ', src, re.M))
        nbc = len(re.findall(rf'^def {tag}_b\d+ ', src, re.M))
        args = f'{k} {comp[0]} {comp[1]} {comp[2]}'
        C = [f'/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.',
             f'   Kernel checks of the M0 certificate {tag}: recorded permutations (permOKB) and blockers',
             f'   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/',
             'import RootedM4.Cover', f'import RootedM4.CoverData.F_{tag}', '',
             'namespace SB.Rooted.M4.CoverData', 'open SB.Rooted.M4.Cover', '']
        for i in range(npc):
            C.append(f'theorem {tag}_p{i}_ok : {tag}_p{i}.all (permOKB {args}) = true := by decide +kernel')
        for i in range(nbc):
            C.append(f'theorem {tag}_b{i}_ok : {tag}_b{i}.all (blockOKB {args}) = true := by decide +kernel')
        C.append('')
        C.append(f'theorem {tag}_ok : FamOK {tag} :=')
        C.append(f'  famOK_of_raw (by decide)')
        C.append('    (by simp only [List.all_append, ' + ', '.join(f'{tag}_p{i}_ok' for i in range(npc)) + ', Bool.and_self])')
        C.append('    (by simp only [List.all_append, ' + ', '.join(f'{tag}_b{i}_ok' for i in range(nbc)) + ', Bool.and_self])')
        C.append('')
        C.append('end SB.Rooted.M4.CoverData')
        C.append(f'#print axioms SB.Rooted.M4.CoverData.{tag}_ok')
        open(os.path.join(CK, f'C_{tag}.lean'), 'w').write('\n'.join(C) + '\n')
    CA = ['/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit. -/']
    CA += [f'import RootedM4.CoverChecks.C_{t}' for t, _, _ in tags]
    CA += ['import RootedM4.CoverData.All', '', 'namespace SB.Rooted.M4.CoverData', 'open SB.Rooted.M4.Cover', '',
           '/-- Every family certificate passes the `validate.py` checks. -/',
           'theorem allCerts_ok : ∀ fc ∈ allCerts, FamOK fc := by',
           '  intro fc hfc',
           '  simp only [allCerts, List.mem_cons, List.not_mem_nil, or_false] at hfc',
           '  rcases hfc with ' + ' | '.join('rfl' for _ in tags),
           '  ' + '\n  '.join(f'· exact {t}_ok' for t, _, _ in tags),
           '', 'end SB.Rooted.M4.CoverData', '#print axioms SB.Rooted.M4.CoverData.allCerts_ok']
    open(os.path.join(CK, 'All.lean'), 'w').write('\n'.join(CA) + '\n')
    print(len(tags), 'families written to', OUT)


if __name__ == '__main__':
    main()
