/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit. -/
import RootedM4.CoverChecks.C_k10_c0100
import RootedM4.CoverChecks.C_k10_c019
import RootedM4.CoverChecks.C_k10_c028
import RootedM4.CoverChecks.C_k10_c037
import RootedM4.CoverChecks.C_k10_c046
import RootedM4.CoverChecks.C_k10_c055
import RootedM4.CoverChecks.C_k10_c064
import RootedM4.CoverChecks.C_k10_c073
import RootedM4.CoverChecks.C_k10_c082
import RootedM4.CoverChecks.C_k10_c091
import RootedM4.CoverChecks.C_k8_c008
import RootedM4.CoverChecks.C_k8_c017
import RootedM4.CoverChecks.C_k8_c026
import RootedM4.CoverChecks.C_k8_c035
import RootedM4.CoverChecks.C_k8_c044
import RootedM4.CoverChecks.C_k8_c053
import RootedM4.CoverChecks.C_k8_c062
import RootedM4.CoverChecks.C_k8_c071
import RootedM4.CoverChecks.C_k8_c080
import RootedM4.CoverChecks.C_k8_c107
import RootedM4.CoverChecks.C_k8_c116
import RootedM4.CoverChecks.C_k8_c125
import RootedM4.CoverChecks.C_k8_c134
import RootedM4.CoverChecks.C_k8_c143
import RootedM4.CoverChecks.C_k8_c152
import RootedM4.CoverChecks.C_k8_c161
import RootedM4.CoverChecks.C_k8_c170
import RootedM4.CoverChecks.C_k8_c206
import RootedM4.CoverChecks.C_k8_c215
import RootedM4.CoverChecks.C_k8_c224
import RootedM4.CoverChecks.C_k8_c233
import RootedM4.CoverChecks.C_k8_c242
import RootedM4.CoverChecks.C_k8_c251
import RootedM4.CoverChecks.C_k8_c260
import RootedM4.CoverChecks.C_k8_c305
import RootedM4.CoverChecks.C_k8_c314
import RootedM4.CoverChecks.C_k8_c323
import RootedM4.CoverChecks.C_k8_c332
import RootedM4.CoverChecks.C_k8_c341
import RootedM4.CoverChecks.C_k8_c350
import RootedM4.CoverChecks.C_k8_c404
import RootedM4.CoverChecks.C_k8_c413
import RootedM4.CoverChecks.C_k8_c422
import RootedM4.CoverChecks.C_k8_c431
import RootedM4.CoverChecks.C_k8_c440
import RootedM4.CoverChecks.C_k8_c503
import RootedM4.CoverChecks.C_k8_c512
import RootedM4.CoverChecks.C_k8_c521
import RootedM4.CoverChecks.C_k8_c530
import RootedM4.CoverChecks.C_k8_c602
import RootedM4.CoverChecks.C_k8_c611
import RootedM4.CoverChecks.C_k8_c620
import RootedM4.CoverChecks.C_k9_c090
import RootedM4.CoverData.All

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

/-- Every family certificate passes the `validate.py` checks. -/
theorem allCerts_ok : ∀ fc ∈ allCerts, FamOK fc := by
  intro fc hfc
  simp only [allCerts, List.mem_cons, List.not_mem_nil, or_false] at hfc
  rcases hfc with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact k10_c0100_ok
  · exact k10_c019_ok
  · exact k10_c028_ok
  · exact k10_c037_ok
  · exact k10_c046_ok
  · exact k10_c055_ok
  · exact k10_c064_ok
  · exact k10_c073_ok
  · exact k10_c082_ok
  · exact k10_c091_ok
  · exact k8_c008_ok
  · exact k8_c017_ok
  · exact k8_c026_ok
  · exact k8_c035_ok
  · exact k8_c044_ok
  · exact k8_c053_ok
  · exact k8_c062_ok
  · exact k8_c071_ok
  · exact k8_c080_ok
  · exact k8_c107_ok
  · exact k8_c116_ok
  · exact k8_c125_ok
  · exact k8_c134_ok
  · exact k8_c143_ok
  · exact k8_c152_ok
  · exact k8_c161_ok
  · exact k8_c170_ok
  · exact k8_c206_ok
  · exact k8_c215_ok
  · exact k8_c224_ok
  · exact k8_c233_ok
  · exact k8_c242_ok
  · exact k8_c251_ok
  · exact k8_c260_ok
  · exact k8_c305_ok
  · exact k8_c314_ok
  · exact k8_c323_ok
  · exact k8_c332_ok
  · exact k8_c341_ok
  · exact k8_c350_ok
  · exact k8_c404_ok
  · exact k8_c413_ok
  · exact k8_c422_ok
  · exact k8_c431_ok
  · exact k8_c440_ok
  · exact k8_c503_ok
  · exact k8_c512_ok
  · exact k8_c521_ok
  · exact k8_c530_ok
  · exact k8_c602_ok
  · exact k8_c611_ok
  · exact k8_c620_ok
  · exact k9_c090_ok

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.allCerts_ok
