/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k10_c082: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). 
   Edited 2026-10-07 (M5): the 79 per-chunk checks moved unchanged to C_k10_c082_0.._7 (memory). -/
import RootedM4.CoverChecks.C_k10_c082_0
import RootedM4.CoverChecks.C_k10_c082_1
import RootedM4.CoverChecks.C_k10_c082_2
import RootedM4.CoverChecks.C_k10_c082_3
import RootedM4.CoverChecks.C_k10_c082_4
import RootedM4.CoverChecks.C_k10_c082_5
import RootedM4.CoverChecks.C_k10_c082_6
import RootedM4.CoverChecks.C_k10_c082_7

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k10_c082_ok : FamOK k10_c082 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k10_c082_p0_ok, k10_c082_p1_ok, Bool.and_self])
    (by simp only [List.all_append, k10_c082_b0_ok, k10_c082_b1_ok, k10_c082_b2_ok, k10_c082_b3_ok, k10_c082_b4_ok, k10_c082_b5_ok, k10_c082_b6_ok, k10_c082_b7_ok, k10_c082_b8_ok, k10_c082_b9_ok, k10_c082_b10_ok, k10_c082_b11_ok, k10_c082_b12_ok, k10_c082_b13_ok, k10_c082_b14_ok, k10_c082_b15_ok, k10_c082_b16_ok, k10_c082_b17_ok, k10_c082_b18_ok, k10_c082_b19_ok, k10_c082_b20_ok, k10_c082_b21_ok, k10_c082_b22_ok, k10_c082_b23_ok, k10_c082_b24_ok, k10_c082_b25_ok, k10_c082_b26_ok, k10_c082_b27_ok, k10_c082_b28_ok, k10_c082_b29_ok, k10_c082_b30_ok, k10_c082_b31_ok, k10_c082_b32_ok, k10_c082_b33_ok, k10_c082_b34_ok, k10_c082_b35_ok, k10_c082_b36_ok, k10_c082_b37_ok, k10_c082_b38_ok, k10_c082_b39_ok, k10_c082_b40_ok, k10_c082_b41_ok, k10_c082_b42_ok, k10_c082_b43_ok, k10_c082_b44_ok, k10_c082_b45_ok, k10_c082_b46_ok, k10_c082_b47_ok, k10_c082_b48_ok, k10_c082_b49_ok, k10_c082_b50_ok, k10_c082_b51_ok, k10_c082_b52_ok, k10_c082_b53_ok, k10_c082_b54_ok, k10_c082_b55_ok, k10_c082_b56_ok, k10_c082_b57_ok, k10_c082_b58_ok, k10_c082_b59_ok, k10_c082_b60_ok, k10_c082_b61_ok, k10_c082_b62_ok, k10_c082_b63_ok, k10_c082_b64_ok, k10_c082_b65_ok, k10_c082_b66_ok, k10_c082_b67_ok, k10_c082_b68_ok, k10_c082_b69_ok, k10_c082_b70_ok, k10_c082_b71_ok, k10_c082_b72_ok, k10_c082_b73_ok, k10_c082_b74_ok, k10_c082_b75_ok, k10_c082_b76_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k10_c082_ok
