/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k10_c091: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/
import RootedM4.Cover
import RootedM4.CoverData.F_k10_c091

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k10_c091_p0_ok : k10_c091_p0.all (permOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_p1_ok : k10_c091_p1.all (permOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b0_ok : k10_c091_b0.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b1_ok : k10_c091_b1.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b2_ok : k10_c091_b2.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b3_ok : k10_c091_b3.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b4_ok : k10_c091_b4.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b5_ok : k10_c091_b5.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b6_ok : k10_c091_b6.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b7_ok : k10_c091_b7.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b8_ok : k10_c091_b8.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b9_ok : k10_c091_b9.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b10_ok : k10_c091_b10.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b11_ok : k10_c091_b11.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b12_ok : k10_c091_b12.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b13_ok : k10_c091_b13.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b14_ok : k10_c091_b14.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b15_ok : k10_c091_b15.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b16_ok : k10_c091_b16.all (blockOKB 10 0 9 1) = true := by decide +kernel
theorem k10_c091_b17_ok : k10_c091_b17.all (blockOKB 10 0 9 1) = true := by decide +kernel

theorem k10_c091_ok : FamOK k10_c091 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k10_c091_p0_ok, k10_c091_p1_ok, Bool.and_self])
    (by simp only [List.all_append, k10_c091_b0_ok, k10_c091_b1_ok, k10_c091_b2_ok, k10_c091_b3_ok, k10_c091_b4_ok, k10_c091_b5_ok, k10_c091_b6_ok, k10_c091_b7_ok, k10_c091_b8_ok, k10_c091_b9_ok, k10_c091_b10_ok, k10_c091_b11_ok, k10_c091_b12_ok, k10_c091_b13_ok, k10_c091_b14_ok, k10_c091_b15_ok, k10_c091_b16_ok, k10_c091_b17_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k10_c091_ok
