/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k10_c028: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/
import RootedM4.Cover
import RootedM4.CoverData.F_k10_c028

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k10_c028_p0_ok : k10_c028_p0.all (permOKB 10 0 2 8) = true := by decide +kernel
theorem k10_c028_b0_ok : k10_c028_b0.all (blockOKB 10 0 2 8) = true := by decide +kernel

theorem k10_c028_ok : FamOK k10_c028 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k10_c028_p0_ok, Bool.and_self])
    (by simp only [List.all_append, k10_c028_b0_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k10_c028_ok
