/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k10_c0100: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/
import RootedM4.Cover
import RootedM4.CoverData.F_k10_c0100

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k10_c0100_p0_ok : k10_c0100_p0.all (permOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_p1_ok : k10_c0100_p1.all (permOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_p2_ok : k10_c0100_p2.all (permOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b0_ok : k10_c0100_b0.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b1_ok : k10_c0100_b1.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b2_ok : k10_c0100_b2.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b3_ok : k10_c0100_b3.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b4_ok : k10_c0100_b4.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b5_ok : k10_c0100_b5.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b6_ok : k10_c0100_b6.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b7_ok : k10_c0100_b7.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b8_ok : k10_c0100_b8.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b9_ok : k10_c0100_b9.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b10_ok : k10_c0100_b10.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b11_ok : k10_c0100_b11.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b12_ok : k10_c0100_b12.all (blockOKB 10 0 10 0) = true := by decide +kernel
theorem k10_c0100_b13_ok : k10_c0100_b13.all (blockOKB 10 0 10 0) = true := by decide +kernel

theorem k10_c0100_ok : FamOK k10_c0100 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k10_c0100_p0_ok, k10_c0100_p1_ok, k10_c0100_p2_ok, Bool.and_self])
    (by simp only [List.all_append, k10_c0100_b0_ok, k10_c0100_b1_ok, k10_c0100_b2_ok, k10_c0100_b3_ok, k10_c0100_b4_ok, k10_c0100_b5_ok, k10_c0100_b6_ok, k10_c0100_b7_ok, k10_c0100_b8_ok, k10_c0100_b9_ok, k10_c0100_b10_ok, k10_c0100_b11_ok, k10_c0100_b12_ok, k10_c0100_b13_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k10_c0100_ok
