/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k8_c323: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/
import RootedM4.Cover
import RootedM4.CoverData.F_k8_c323

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k8_c323_p0_ok : k8_c323_p0.all (permOKB 8 3 2 3) = true := by decide +kernel
theorem k8_c323_b0_ok : k8_c323_b0.all (blockOKB 8 3 2 3) = true := by decide +kernel
theorem k8_c323_b1_ok : k8_c323_b1.all (blockOKB 8 3 2 3) = true := by decide +kernel

theorem k8_c323_ok : FamOK k8_c323 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k8_c323_p0_ok, Bool.and_self])
    (by simp only [List.all_append, k8_c323_b0_ok, k8_c323_b1_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k8_c323_ok
