/- Generated by ramsey/runs/k28_rooted/m4_canon/gen_cover_data.py. Do not edit.
   Kernel checks of the M0 certificate k9_c090: recorded permutations (permOKB) and blockers
   (blockOKB: listed, or failing validate.fail_iii on the recorded U). -/
import RootedM4.Cover
import RootedM4.CoverData.F_k9_c090

namespace SB.Rooted.M4.CoverData
open SB.Rooted.M4.Cover

theorem k9_c090_p0_ok : k9_c090_p0.all (permOKB 9 0 9 0) = true := by decide +kernel
theorem k9_c090_b0_ok : k9_c090_b0.all (blockOKB 9 0 9 0) = true := by decide +kernel

theorem k9_c090_ok : FamOK k9_c090 :=
  famOK_of_raw (by decide)
    (by simp only [List.all_append, k9_c090_p0_ok, Bool.and_self])
    (by simp only [List.all_append, k9_c090_b0_ok, Bool.and_self])

end SB.Rooted.M4.CoverData
#print axioms SB.Rooted.M4.CoverData.k9_c090_ok
