/-
# `R(K_{2,11}, K_{2,3}) = 22`, Comparator-grade route: no `native_decide`

The same composition as `FaithfulK35K25Comparator.lean`, for the cell `k211k23_n22`:
* `LRATCatcher.Comparator.K211K23.encoded_unsat` (module `LRATCatcher.ComparatorUnsatK211K23`): the Lean encoder's own
  output `toCNF (encodeBip 22 2 11 2 3)` is unsatisfiable, through two named axioms, `leaves_cakelpr`
  (1,313 leaf files) and `cover_cakelpr`, each discharged outside Lean by cake_lpr on DIMACS printed from the
  Lean terms;
* `SB.BipBridge.no_colouring_of_toCNFV_unsat` (`lean/sbsound`): unsatisfiability of the encoding refutes every
  good 2-colouring (encoding soundness and vertex-lex symmetry breaking; standard axioms only);
* `SB.Witness21b.witness_kernel` (`lean/sbsound`, generated by `gen_witness_kernel.py` from `k211k23-n22/witness/`): an
  explicit good colouring of `K_21`, checked by `decide +kernel`.
-/
import LRATCatcher.ComparatorUnsatK211K23
import Sbsound.BipBridge
import Sbsound.Witness21bKernel

namespace LRATCatcher.FaithfulK211K23

open SB

/-! The vendored copy of the encoder is the original. Every definition except `combos`
is identified by `rfl`; `combos` is structurally recursive and the elaborator's smart
unfolding does not compare two separately compiled copies, so it is identified by
recursion on its own equations, and the two definitions built on it follow by rewriting. -/

theorem combos_eq : ∀ (k : ℕ) (l : List ℕ),
    SB.Encoder.combos k l = LRATCatcher.Encoder.combos k l
  | 0, [] => rfl
  | 0, _ :: _ => rfl
  | _ + 1, [] => rfl
  | k + 1, x :: xs => by
    simp only [SB.Encoder.combos, LRATCatcher.Encoder.combos]
    rw [combos_eq k xs, combos_eq (k + 1) xs]

theorem combos_eq' : SB.Encoder.combos = LRATCatcher.Encoder.combos := by
  funext k l; exact combos_eq k l

theorem codegreeColour_eq :
    SB.Encoder.codegreeColour = LRATCatcher.Encoder.codegreeColour := by
  funext n r c s t nv0
  unfold SB.Encoder.codegreeColour LRATCatcher.Encoder.codegreeColour
  rw [combos_eq']
  rfl

theorem encodeBip_eq (n s₀ t₀ s₁ t₁ : ℕ) :
    SB.Encoder.encodeBip n s₀ t₀ s₁ t₁ = LRATCatcher.Encoder.encodeBip n s₀ t₀ s₁ t₁ := by
  unfold SB.Encoder.encodeBip LRATCatcher.Encoder.encodeBip
  rw [codegreeColour_eq]
  rfl

/-- The vendored DIMACS conversion is `LRATCatcher.Encoder.toCNF`, definitionally
(both convert a literal by `l ↦ (|l| - 1, decide (0 < l))`). -/
theorem toCNF_eq (cs : List (List Int)) :
    SB.BipBridge.toCNFV cs = LRATCatcher.Encoder.toCNF cs := rfl

/-- The cake_lpr-certified `encoded_unsat`, restated on the vendored definitions. -/
theorem vendored_unsat : (SB.BipBridge.toCNFV (SB.Encoder.encodeBip 22 2 11 2 3)).Unsat := by
  rw [toCNF_eq, encodeBip_eq]
  exact LRATCatcher.Comparator.K211K23.encoded_unsat

/-- **No 2-colouring of `K_22` avoids `K_{2,11}` in colour 0 and `K_{2,3}` in colour 1.** -/
theorem no_good_colouring_K22 :
    ¬ ∃ a : EColouring 22 2, NoKst a 0 2 11 ∧ NoKst a 1 2 3 :=
  SB.BipBridge.no_colouring_of_toCNFV_unsat (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) vendored_unsat

/-- **`R(K_{2,11}, K_{2,3}) = 22`**: no good colouring of `K_22`, and an explicit good colouring of
`K_21`. -/
theorem k211k23_eq_22 :
    (¬ ∃ a : EColouring 22 2, NoKst a 0 2 11 ∧ NoKst a 1 2 3) ∧
    (∃ a : EColouring 21 2, NoKst a 0 2 11 ∧ NoKst a 1 2 3) :=
  ⟨no_good_colouring_K22,
   ⟨SB.Witness21b.w, SB.Witness21b.witness_kernel.1, SB.Witness21b.witness_kernel.2⟩⟩

end LRATCatcher.FaithfulK211K23

#print axioms LRATCatcher.FaithfulK211K23.no_good_colouring_K22
#print axioms LRATCatcher.FaithfulK211K23.k211k23_eq_22
