import Sbsound.Codegree

/-!
# A concrete witness: `R(K_{2,11}, K_{2,4}) > 25`, checked by the kernel

Generated by `gen_witness_kernel.py` from the deposited coloring (its color 1 is color `0` here, its
color 2 is color `1`), with the same structure as `Witness21Kernel.lean`: the table is one natural
number `MASK` (bit `u * 25 + v` is set iff `{u, v}` has color `1`), `bb_symm` checks its symmetry, and
common neighbours are counted over sorted tuples. Every evaluation is `decide +kernel`.
-/

namespace SB.Witness25

open SB

abbrev Vtx := Fin 25

def MASK : Nat := 7748241056852952571283580306445202844738057315624460271687187743267212112044957276035363670076302431140132143326266399373769686586668881942092961859974099417280567822361288530773278286024

def bb (u v : Vtx) : Bool := Nat.testBit MASK (u.val * 25 + v.val)

set_option maxRecDepth 100000 in
theorem bb_symm : ∀ u v : Vtx, bb u v = bb v u := by decide +kernel

def w : EColouring 25 2 := fun e => cond (bb (ofLex e.val).1 (ofLex e.val).2) 1 0

lemma eval_w_mkEdge {u v : Vtx} (h : u ≠ v) : w (mkEdge u v h) = cond (bb u v) 1 0 := by
  rcases lt_or_gt_of_ne h with hl | hg
  · rw [mkEdge_pos h hl]; rfl
  · rw [mkEdge_neg h hg, bb_symm u v]; rfl

lemma eq_c_iff {c : Fin 2} (b : Bool) :
    (cond b 1 0 = c) ↔ (decide b = decide (c == 1)) := by
  revert b
  fin_cases c <;> intros b <;> cases b <;> simp [Fin.isValue]

def isC (c : Fin 2) (u v : Vtx) : Bool :=
  decide (u ≠ v) && decide (bb u v = (c == 1))

lemma colourRel_iff_isC (c : Fin 2) (u v : Vtx) :
    colourRel w c u v ↔ isC c u v = true := by
  constructor
  · rintro ⟨hne, hc⟩
    rw [eval_w_mkEdge hne, eq_c_iff] at hc
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq]
    exact ⟨hne, by simpa using hc⟩
  · intro h
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq] at h
    refine ⟨h.1, ?_⟩
    rw [eval_w_mkEdge h.1]
    exact (eq_c_iff _).mpr (by simpa using h.2)

def cnt2 (c : Fin 2) (a b : Vtx) : Nat :=
  (List.finRange 25).countP fun v => decide (v ≠ a) && decide (v ≠ b) && isC c a v && isC c b v

theorem card_commonNbrs2 (c : Fin 2) (a b : Vtx) :
    (commonNbrs w c {a, b}).card = cnt2 c a b := by
  rw [commonNbrs, Finset.card_def, Finset.filter_val, ← Multiset.countP_eq_card_filter,
    Finset.val_univ_fin, Multiset.coe_countP, cnt2]
  apply List.countP_congr
  intro v _
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or, forall_eq_or_imp, forall_eq,
    colourRel_iff_isC, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  tauto

theorem smallCodegree2_of_cnt (c : Fin 2) (t : ℕ)
    (h : ∀ a b : Vtx, a < b → cnt2 c a b < t) : SmallCodegree w c 2 t := by
  intro S hS
  obtain ⟨x, y, hxy, rfl⟩ := Finset.card_eq_two.mp (Finset.mem_powersetCard.mp hS).2
  rcases lt_or_gt_of_ne hxy with hl | hg
  · rw [card_commonNbrs2]; exact h x y hl
  · rw [Finset.pair_comm, card_commonNbrs2]; exact h y x hg

set_option maxRecDepth 100000 in
theorem cnt2_0211 : ∀ a b : Vtx, a < b → cnt2 0 a b < 11 := by decide +kernel

set_option maxRecDepth 100000 in
theorem cnt2_124 : ∀ a b : Vtx, a < b → cnt2 1 a b < 4 := by decide +kernel

/-- **The witness theorem, kernel-checked.** `w` has no `K_{2,11}` in color `0` and no `K_{2,4}` in
color `1`, so `R(K_{2,11}, K_{2,4}) > 25`. -/
theorem witness_kernel : NoKst w 0 2 11 ∧ NoKst w 1 2 4 :=
  ⟨(codegree_iff w 0 2 11).mpr (smallCodegree2_of_cnt 0 11 cnt2_0211),
   (codegree_iff w 1 2 4).mpr (smallCodegree2_of_cnt 1 4 cnt2_124)⟩

end SB.Witness25

#print axioms SB.Witness25.witness_kernel
