import Sbsound.Codegree

/-!
# A concrete witness: `R(K_{3,5}, K_{2,4}) > 18`, checked by the kernel

Generated by `gen_witness_kernel.py` from the deposited coloring (its color 1 is color `0` here, its
color 2 is color `1`), with the same structure as `Witness21Kernel.lean`: the table is one natural
number `MASK` (bit `u * 18 + v` is set iff `{u, v}` has color `1`), `bb_symm` checks its symmetry, and
common neighbours are counted over sorted tuples. Every evaluation is `decide +kernel`.
-/

namespace SB.Witness18b

open SB

abbrev Vtx := Fin 18

def MASK : Nat := 13021084722233905604398881666751986922357334648996063113808776637870431426545619836678801329393784

def bb (u v : Vtx) : Bool := Nat.testBit MASK (u.val * 18 + v.val)

set_option maxRecDepth 100000 in
theorem bb_symm : ∀ u v : Vtx, bb u v = bb v u := by decide +kernel

def w : EColouring 18 2 := fun e => cond (bb (ofLex e.val).1 (ofLex e.val).2) 1 0

lemma eval_w_mkEdge {u v : Vtx} (h : u ≠ v) : w (mkEdge u v h) = cond (bb u v) 1 0 := by
  rcases lt_or_gt_of_ne h with hl | hg
  · rw [mkEdge_pos h hl]; rfl
  · rw [mkEdge_neg h hg, bb_symm u v]; rfl

lemma eq_c_iff {c : Fin 2} (b : Bool) :
    (cond b 1 0 = c) ↔ (decide b = decide (c == 1)) := by
  revert b
  fin_cases c <;> intros b <;> cases b <;> simp [Fin.isValue]

def isC (c : Fin 2) (u v : Vtx) : Bool :=
  decide (u ≠ v) && decide (bb u v = (c == 1))

lemma colourRel_iff_isC (c : Fin 2) (u v : Vtx) :
    colourRel w c u v ↔ isC c u v = true := by
  constructor
  · rintro ⟨hne, hc⟩
    rw [eval_w_mkEdge hne, eq_c_iff] at hc
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq]
    exact ⟨hne, by simpa using hc⟩
  · intro h
    simp only [isC, Bool.and_eq_true, decide_eq_true_eq] at h
    refine ⟨h.1, ?_⟩
    rw [eval_w_mkEdge h.1]
    exact (eq_c_iff _).mpr (by simpa using h.2)

def cnt3 (c : Fin 2) (a b d : Vtx) : Nat :=
  (List.finRange 18).countP fun v => decide (v ≠ a) && decide (v ≠ b) && decide (v ≠ d)
    && isC c a v && isC c b v && isC c d v

theorem card_commonNbrs3 (c : Fin 2) (a b d : Vtx) :
    (commonNbrs w c {a, b, d}).card = cnt3 c a b d := by
  rw [commonNbrs, Finset.card_def, Finset.filter_val, ← Multiset.countP_eq_card_filter,
    Finset.val_univ_fin, Multiset.coe_countP, cnt3]
  apply List.countP_congr
  intro v _
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or, forall_eq_or_imp, forall_eq,
    colourRel_iff_isC, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  tauto

theorem triple_sorted {x y z : Vtx} (hxy : x ≠ y) (hxz : x ≠ z) (hyz : y ≠ z) :
    ∃ a b d : Vtx, a < b ∧ b < d ∧ ({x, y, z} : Finset Vtx) = {a, b, d} := by
  rcases lt_or_gt_of_ne hxy with h1 | h1 <;>
  rcases lt_or_gt_of_ne hxz with h2 | h2 <;>
  rcases lt_or_gt_of_ne hyz with h3 | h3
  all_goals first
    | exact ⟨x, y, z, by assumption, by assumption, rfl⟩
    | exact ⟨x, z, y, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨y, x, z, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨y, z, x, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨z, x, y, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩
    | exact ⟨z, y, x, by assumption, by assumption, by ext; simp only [Finset.mem_insert, Finset.mem_singleton]; tauto⟩

theorem smallCodegree3_of_cnt (c : Fin 2) (t : ℕ)
    (h : ∀ a b d : Vtx, a < b → b < d → cnt3 c a b d < t) : SmallCodegree w c 3 t := by
  intro S hS
  obtain ⟨x, y, z, hxy, hxz, hyz, rfl⟩ :=
    Finset.card_eq_three.mp (Finset.mem_powersetCard.mp hS).2
  obtain ⟨a, b, d, hab, hbd, he⟩ := triple_sorted hxy hxz hyz
  rw [he, card_commonNbrs3]
  exact h a b d hab hbd

def cnt2 (c : Fin 2) (a b : Vtx) : Nat :=
  (List.finRange 18).countP fun v => decide (v ≠ a) && decide (v ≠ b) && isC c a v && isC c b v

theorem card_commonNbrs2 (c : Fin 2) (a b : Vtx) :
    (commonNbrs w c {a, b}).card = cnt2 c a b := by
  rw [commonNbrs, Finset.card_def, Finset.filter_val, ← Multiset.countP_eq_card_filter,
    Finset.val_univ_fin, Multiset.coe_countP, cnt2]
  apply List.countP_congr
  intro v _
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or, forall_eq_or_imp, forall_eq,
    colourRel_iff_isC, Bool.and_eq_true, decide_eq_true_eq, ne_eq]
  tauto

theorem smallCodegree2_of_cnt (c : Fin 2) (t : ℕ)
    (h : ∀ a b : Vtx, a < b → cnt2 c a b < t) : SmallCodegree w c 2 t := by
  intro S hS
  obtain ⟨x, y, hxy, rfl⟩ := Finset.card_eq_two.mp (Finset.mem_powersetCard.mp hS).2
  rcases lt_or_gt_of_ne hxy with hl | hg
  · rw [card_commonNbrs2]; exact h x y hl
  · rw [Finset.pair_comm, card_commonNbrs2]; exact h y x hg

set_option maxRecDepth 100000 in
theorem cnt3_035 : ∀ a b d : Vtx, a < b → b < d → cnt3 0 a b d < 5 := by decide +kernel

set_option maxRecDepth 100000 in
theorem cnt2_124 : ∀ a b : Vtx, a < b → cnt2 1 a b < 4 := by decide +kernel

/-- **The witness theorem, kernel-checked.** `w` has no `K_{3,5}` in color `0` and no `K_{2,4}` in
color `1`, so `R(K_{3,5}, K_{2,4}) > 18`. -/
theorem witness_kernel : NoKst w 0 3 5 ∧ NoKst w 1 2 4 :=
  ⟨(codegree_iff w 0 3 5).mpr (smallCodegree3_of_cnt 0 5 cnt3_035),
   (codegree_iff w 1 2 4).mpr (smallCodegree2_of_cnt 1 4 cnt2_124)⟩

end SB.Witness18b

#print axioms SB.Witness18b.witness_kernel
