#!/usr/bin/env python3
"""Regenerate the derived views from the witness files.

Writes, for each cell listed in CELLS:
  <cell>/witness/matrix.txt   an adjacency matrix in block characters, for reading by eye
and, once, at the repository root:
  bench.html                  a self-contained page that re-checks any coloring in a browser

The witness files are the artifacts. Everything this script writes is derived from them and
can be thrown away and rebuilt:

    python3 tools/gen_views.py

Deterministic: running it twice produces identical bytes. No network, no dependencies.
"""
import os
from itertools import combinations
from math import comb

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Nothing is hard-coded. Every witness under <cell>/witness/witness_*.txt is discovered,
# and each declares its own parameters in its header:
#
#     # spec: K3x5,K2x5      forbidden graph per color, in order
#     # name: K(3,5)/K(2,5) on K21
#
# Drop a new witness in with those two lines and it is picked up on the next run: its
# matrix is written beside it and it appears in bench.html. A witness without a spec is
# an error rather than a silent omission.
import glob
import re


def discover():
    found = []
    for path in sorted(glob.glob(os.path.join(HERE, "*", "witness", "witness_*.txt"))):
        head = [l for l in open(path) if l.startswith("#")]
        spec = next((re.sub(r"^#\s*spec:\s*", "", l).strip() for l in head
                     if l.lstrip("#").strip().startswith("spec:")), None)
        name = next((re.sub(r"^#\s*name:\s*", "", l).strip() for l in head
                     if l.lstrip("#").strip().startswith("name:")), None)
        rel = os.path.relpath(path, HERE)
        if not spec:
            raise SystemExit(f"{rel}: no '# spec:' line in the header. Add one, e.g.\n"
                             f"    # spec: K3x5,K2x5")
        found.append((os.path.dirname(os.path.dirname(rel)), path, spec,
                      name or os.path.basename(rel)))
    if not found:
        raise SystemExit("no witnesses found under */witness/witness_*.txt")
    return found


FULL, LIGHT, DIAG = "\u2588\u2588", "\u2591\u2591", "\u2592\u2592"


def load(path):
    col, n = {}, 0
    for line in open(path):
        if line.startswith("#") or not line.strip():
            continue
        i, j, c = map(int, line.split())
        col[(min(i, j), max(i, j))] = c
        n = max(n, i, j)
    assert len(col) == n * (n - 1) // 2, f"{path}: not a complete K_{n}"
    return n, col


def parse(spec):
    """K3x5 -> complete bipartite, B5 -> book, K4 -> clique.

    The book case used to fall through to the clique branch, which stripped the leading
    letter and read B5 as K_5. Every derived view for a book cell was mislabelled.
    """
    out = []
    for tok in spec.split(","):
        tok = tok.strip()
        if "x" in tok:
            s, t = (int(v) for v in tok[1:].split("x"))
            out.append(("bip", s, t, f"K_{{{s},{t}}}"))
        elif tok[:1].upper() == "B":
            t = int(tok[1:])
            out.append(("book", t, None, f"B_{t}"))
        else:
            k = int(tok[1:])
            out.append(("clique", k, None, f"K_{k}"))
    return out


def matrix(name, n, col, spec, cell):
    def c(i, j):
        return col[(min(i, j), max(i, j))]
    g = parse(spec)
    o = [f"# Adjacency matrix of witness/{os.path.basename(name)}, for reading by eye.",
         f"# Cell R({g[0][3]}, {g[1][3]}): color 1 must contain no {g[0][3]},"
         f" color 2 no {g[1][3]}.", "#",
         f"#   {FULL} color 1     {LIGHT} color 2     {DIAG} diagonal", "#",
         f"# Rows and columns are vertices 1..{n}. Two characters per cell so the grid reads",
         "# roughly square in a monospace font. THE WITNESS FILE IS THE ARTIFACT; this is a",
         "# derived view, regenerated by tools/gen_views.py, so parse that one, not this.",
         "#",
         "     " + "".join(f"{j % 10} " for j in range(1, n + 1))]
    for i in range(1, n + 1):
        o.append(f"  {i:2d} " + "".join(
            DIAG if i == j else (FULL if c(i, j) == 1 else LIGHT) for j in range(1, n + 1)))
    d1 = [sum(1 for w in range(1, n + 1) if w != v and c(v, w) == 1) for v in range(1, n + 1)]
    o += ["", f"# color-1 degree of each vertex 1..{n}: " + " ".join(map(str, d1)),
          f"# color-1 edges {sum(d1)//2}, color-2 edges {n*(n-1)//2 - sum(d1)//2},"
          f" total {n*(n-1)//2}", "#"]
    for gi, (kind, a, b, lab) in enumerate(g, start=1):
        if kind == "book":
            # B_t = K_2 + t*K_1: the pair must itself be an edge of this colour.
            mx = max((sum(1 for w in range(1, n + 1)
                          if w != u and w != v and c(u, w) == gi and c(v, w) == gi)
                      for u in range(1, n + 1) for v in range(u + 1, n + 1)
                      if c(u, v) == gi), default=0)
            o.append(f"# color {gi}: largest common neighborhood of a colour-{gi} EDGE is"
                     f" {mx}; {a} would force {lab}")
        elif kind == "bip":
            V = list(range(1, n + 1))
            mx = max(sum(1 for w in V if w not in A and all(c(x, w) == gi for x in A))
                     for A in combinations(V, a))
            o.append(f"# color {gi}: largest common neighborhood of an {a}-set is {mx};"
                     f" {b} would force {lab}")
    o.append("# The solid block at the top left, where present, is static symmetry breaking in")
    o.append("# the formula showing through: the search was restricted to lex-minimal")
    o.append("# representatives, which sorts vertex 1's neighborhood. It is a fingerprint of")
    o.append("# the search, not a property of the coloring.")
    return "\n".join(o) + "\n"



# --- orbit structure and static SVG ---------------------------------------------
#
# These colorings were found by prescribing an automorphism, so most of them carry a
# nontrivial one. Recovering it here from the coloring ALONE -- rather than trusting a
# note about how the search was run -- keeps the view honest: if the group is trivial the
# picture says so, and the ordering falls back to 1..n.


def find_aut(n, col):
    """The lexicographically smallest non-identity automorphism, or None if the coloring
    is asymmetric. Canonical, so the rendered output is deterministic."""
    def c(i, j):
        return col[(min(i, j), max(i, j))]
    deg = {v: sum(1 for u in range(1, n + 1) if u != v and c(u, v) == 1)
           for v in range(1, n + 1)}
    cls = {}
    for v, d in deg.items():
        cls.setdefault(d, []).append(v)
    best = None

    def bt(k, mp, used):
        nonlocal best
        if best is not None:
            return
        if k > n:
            perm = tuple(mp[v] for v in range(1, n + 1))
            if perm != tuple(range(1, n + 1)):
                best = perm
            return
        for w in sorted(cls.get(deg[k], [])):
            if w in used:
                continue
            if all(c(u, k) == c(mp[u], w) for u in range(1, k)):
                mp[k] = w
                used.add(w)
                bt(k + 1, mp, used)
                del mp[k]
                used.discard(w)
                if best is not None:
                    return
    bt(1, {}, set())
    return best


def cycles(perm):
    n = len(perm)
    seen, out = set(), []
    for v in range(1, n + 1):
        if v in seen:
            continue
        cyc, u = [], v
        while u not in seen:
            seen.add(u)
            cyc.append(u)
            u = perm[u - 1]
        out.append(cyc)
    return out


# Palette matches bench.html. Both hues are legible on GitHub's light and dark canvas,
# which is why the SVG carries no media query: GitHub sanitizes embedded stylesheets in
# markdown, so a theme-switching fill would silently become no fill at all.
E1, E2, DIAGC = "#3E6FB0", "#C89B4A", "#9BA3B4"


def svg(n, col, spec, sigma):
    def c(i, j):
        return col[(min(i, j), max(i, j))]
    orb = cycles(sigma) if sigma else [[v] for v in range(1, n + 1)]
    order = [v for cyc in orb for v in cyc]
    bounds, acc = [], 0
    for cyc in orb:
        acc += len(cyc)
        bounds.append(acc)

    CELL, GAP, PAD, TOP = 9, 26, 8, 20
    grid = n * CELL
    W = PAD + grid + GAP + grid + PAD
    H = TOP + grid + PAD

    def panel(x0, ordering, label):
        out = [f'<text x="{x0}" y="13" font-family="ui-monospace,monospace" '
               f'font-size="11" fill="#8A90A0">{label}</text>']
        for a in range(n):
            for b in range(n):
                i, j = ordering[a], ordering[b]
                f = DIAGC if i == j else (E1 if c(i, j) == 1 else E2)
                out.append(f'<rect x="{x0 + b * CELL}" y="{TOP + a * CELL}" '
                           f'width="{CELL}" height="{CELL}" fill="{f}"/>')
        return out

    body = panel(PAD, list(range(1, n + 1)), f"vertices 1..{n}")
    body += panel(PAD + grid + GAP, order,
                  "grouped by orbit" if sigma else "no symmetry to group by")
    if sigma:
        x0 = PAD + grid + GAP
        for bd in bounds[:-1]:
            o = bd * CELL
            body.append(f'<line x1="{x0}" y1="{TOP + o}" x2="{x0 + grid}" y2="{TOP + o}" '
                        f'stroke="#FFFFFF" stroke-width="1.4" stroke-opacity=".85"/>')
            body.append(f'<line x1="{x0 + o}" y1="{TOP}" x2="{x0 + o}" y2="{TOP + grid}" '
                        f'stroke="#FFFFFF" stroke-width="1.4" stroke-opacity=".85"/>')
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
            f'viewBox="0 0 {W} {H}" role="img">' + "".join(body) + "</svg>\n")


def main():
    ex = {}
    for cell, wpath, spec, disp in discover():
        n, col = load(wpath)
        mpath = os.path.join(os.path.dirname(wpath), "matrix.txt")
        open(mpath, "w").write(matrix(wpath, n, col, spec, cell))
        print(f"  {os.path.relpath(mpath, HERE):42s} K_{n}, {len(col)} edges")
        readme = os.path.join(HERE, cell, "README.md")
        if os.path.exists(readme):
            txt = open(readme).read()
            a, b = "<!-- matrix:start -->", "<!-- matrix:end -->"
            if a in txt and b in txt:
                body = "\n".join(l for l in open(mpath).read().split("\n")
                                 if not l.startswith("#"))
                block = a + "\n```\n" + body.strip("\n") + "\n```\n" + b
                open(readme, "w").write(txt[:txt.index(a)] + block + txt[txt.index(b)+len(b):])
                print(f"  {os.path.relpath(readme, HERE):42s} matrix block refreshed")
        sigma = find_aut(n, col)
        spath = os.path.join(os.path.dirname(wpath), "coloring.svg")
        open(spath, "w").write(svg(n, col, spec, sigma))
        cyc = cycles(sigma) if sigma else []
        shape = "+".join(str(len(x)) for x in sorted(cyc, key=len, reverse=True)) if cyc else "trivial"
        print(f"  {os.path.relpath(spath, HERE):42s} orbits {shape}")
        if os.path.exists(readme):
            txt = open(readme).read()
            a, b = "<!-- svg:start -->", "<!-- svg:end -->"
            if a in txt and b in txt:
                cap = (f"Left, vertices in their original order 1..{n}. Right, the same coloring "
                       f"with vertices grouped by the orbits of a recovered automorphism "
                       f"({shape}); white rules mark the orbit boundaries. Relabeling never "
                       f"changes an edge's color."
                       if cyc else
                       f"Vertices 1..{n}. This coloring has no nontrivial automorphism, so both "
                       f"panels are the same and there is nothing to group by.")
                block = (a + "\n<img src=\"witness/coloring.svg\" alt=\"adjacency matrix of the "
                         f"coloring of K_{n}\" width=\"100%\">\n\n" + cap + "\n" + b)
                open(readme, "w").write(txt[:txt.index(a)] + block + txt[txt.index(b) + len(b):])
        rows = [f"{i} {j} {col[(i, j)]}" for i in range(1, n + 1) for j in range(i + 1, n + 1)]
        ex[disp] = {"name": disp, "spec": spec, "data": "\n".join(rows)}
    import json
    page = HEAD + "<script>\nconst EXAMPLES=" + json.dumps(ex) + ";\n</script>" + TAIL
    open(os.path.join(HERE, "bench.html"), "w").write(page)
    print(f"  bench.html               {len(page):,} bytes, {len(ex)} colorings embedded")


HEAD = r"""<title>Ramsey Witness Bench</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root{
  --ground:#FBFBFC; --panel:#FFFFFF; --sunk:#F3F4F7;
  --ink:#16181D; --ink-2:#585F6C; --ink-3:#8A90A0;
  --rule:#E2E5EC; --rule-2:#CDD2DD;
  --e1:#3E6FB0; --e1-dim:#C8D6E8; --e1-hot:#28518A;
  --e2:#C89B4A; --e2-dim:#EEE3CC; --e2-hot:#9A7530;
  --ok:#2E7D5B; --ok-bg:#E7F2EC; --bad:#B4443A; --bad-bg:#F8E9E7;
  --sans:"IBM Plex Sans",system-ui,sans-serif; --mono:"IBM Plex Mono",ui-monospace,monospace;
}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
  --ground:#131519; --panel:#1A1D23; --sunk:#212530;
  --ink:#EDEFF3; --ink-2:#A2AAB8; --ink-3:#6E7686;
  --rule:#2B303A; --rule-2:#3C424F;
  --e1:#5B8FD4; --e1-dim:#293748; --e1-hot:#8FB6E8;
  --e2:#D6AE63; --e2-dim:#3A3223; --e2-hot:#EAC98A;
  --ok:#5BB98C; --ok-bg:#1B2E26; --bad:#E0776C; --bad-bg:#33211F;
}}
:root[data-theme="dark"]{
  --ground:#131519; --panel:#1A1D23; --sunk:#212530;
  --ink:#EDEFF3; --ink-2:#A2AAB8; --ink-3:#6E7686;
  --rule:#2B303A; --rule-2:#3C424F;
  --e1:#5B8FD4; --e1-dim:#293748; --e1-hot:#8FB6E8;
  --e2:#D6AE63; --e2-dim:#3A3223; --e2-hot:#EAC98A;
  --ok:#5BB98C; --ok-bg:#1B2E26; --bad:#E0776C; --bad-bg:#33211F;
}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);
     font-size:15px;line-height:1.6;-webkit-font-smoothing:antialiased}
.wrap{max-width:1100px;margin:0 auto;padding:38px 24px 72px}
header{border-bottom:1px solid var(--rule);padding-bottom:20px;margin-bottom:26px}
h1{font-size:23px;font-weight:600;margin:0 0 5px;letter-spacing:-.01em;text-wrap:balance}
.lede{color:var(--ink-2);margin:0;max-width:62ch;font-size:14.5px}
.cols{display:grid;grid-template-columns:minmax(280px,340px) 1fr;gap:28px;align-items:start}
@media(max-width:820px){.cols{grid-template-columns:1fr}}
.panel{background:var(--panel);border:1px solid var(--rule);border-radius:10px;padding:18px}
label{display:block;font-size:11.5px;font-weight:500;letter-spacing:.07em;text-transform:uppercase;
      color:var(--ink-3);margin-bottom:6px}
textarea,input,select{width:100%;font-family:var(--mono);font-size:12.5px;background:var(--sunk);
      color:var(--ink);border:1px solid var(--rule-2);border-radius:6px;padding:9px 10px}
textarea{height:150px;resize:vertical;line-height:1.45}
:focus-visible{outline:2px solid var(--e1);outline-offset:1px}
.row{display:flex;gap:9px;margin-top:13px;flex-wrap:wrap}
button{font-family:var(--sans);font-size:13.5px;font-weight:500;padding:8px 15px;border-radius:6px;
       border:1px solid var(--rule-2);background:var(--panel);color:var(--ink);cursor:pointer}
button.primary{background:var(--e1);border-color:var(--e1);color:#fff}
button:hover{border-color:var(--ink-3)}
.chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}
.chip{font-size:12px;padding:4px 9px;border-radius:20px;border:1px solid var(--rule-2);
      background:var(--sunk);color:var(--ink-2);cursor:pointer}
.chip:hover{border-color:var(--e1);color:var(--e1)}
.verdict{display:flex;align-items:center;gap:10px;padding:13px 15px;border-radius:8px;margin-bottom:16px;
         font-weight:500;font-size:15px}
.verdict.ok{background:var(--ok-bg);color:var(--ok)} .verdict.bad{background:var(--bad-bg);color:var(--bad)}
.verdict.idle{background:var(--sunk);color:var(--ink-2);font-weight:400}
.dot{width:9px;height:9px;border-radius:50%;background:currentColor;flex:none}
table{width:100%;border-collapse:collapse;font-size:13.5px;margin-top:4px}
th,td{text-align:left;padding:7px 0;border-bottom:1px solid var(--rule)}
th{font-size:11.5px;font-weight:500;letter-spacing:.06em;text-transform:uppercase;color:var(--ink-3)}
td.num{font-family:var(--mono);font-variant-numeric:tabular-nums;text-align:right}
canvas{display:block;max-width:100%;border:1px solid var(--rule);border-radius:8px;background:var(--panel)}
.legend{display:flex;gap:16px;margin-top:11px;font-size:12.5px;color:var(--ink-2);flex-wrap:wrap;align-items:center}
.sw{width:12px;height:12px;border-radius:3px;display:inline-block;vertical-align:-1px;margin-right:6px}
.nav{display:flex;gap:8px;align-items:center;margin-top:14px;flex-wrap:wrap;font-size:13.5px}
.nav .mono{font-family:var(--mono);color:var(--ink);min-width:11em}
.hint{font-size:12.5px;color:var(--ink-3);margin-top:9px;line-height:1.55}
.err{color:var(--bad);font-size:13px;margin-top:8px}
h2{font-size:15px;font-weight:600;margin:0 0 12px}
.note{border-top:1px solid var(--rule);margin-top:34px;padding-top:20px;color:var(--ink-2);
      font-size:13.5px;max-width:70ch}
.note code{font-family:var(--mono);font-size:12.5px;background:var(--sunk);padding:1px 5px;border-radius:3px}
@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
</style>
<div class="wrap">
<header>
  <h1>Ramsey Witness Bench</h1>
  <p class="lede">Paste an edge coloring, name the graphs it must avoid, and check it. The verification
  runs here in your browser, independently of whatever produced the coloring.</p>
</header>
<div class="cols">
  <div>
    <div class="panel">
      <label for="spec">Avoid, per color</label>
      <input id="spec" value="K3x5,K2x5" spellcheck="false">
      <div class="hint"><code>K3x5</code> is complete bipartite K<sub>3,5</sub>; <code>K3</code> is a
      triangle, <code>K4</code> a clique on 4. One entry per color, comma separated.</div>
      <label for="wit" style="margin-top:16px">Coloring &mdash; one edge per line, <code>i j c</code></label>
      <textarea id="wit" spellcheck="false"></textarea>
      <div class="row">
        <button class="primary" id="run">Check it</button>
        <button id="clear">Clear</button>
      </div>
      <div id="err" class="err"></div>
      <label style="margin-top:17px">Load an example</label>
      <div class="chips" id="chips"></div>
    </div>
  </div>
  <div>
    <div id="verdict" class="verdict idle"><span class="dot"></span><span id="vtext">Nothing checked yet.</span></div>
    <canvas id="cv" width="620" height="620"></canvas>
    <div class="legend">
      <span><span class="sw" style="background:var(--e1)"></span>color 1</span>
      <span><span class="sw" style="background:var(--e2)"></span>color 2</span>
      <span id="hover" style="font-family:var(--mono);color:var(--ink-3)"></span>
    </div>
    <div class="nav">
      <span style="color:var(--ink-3);font-size:11.5px;letter-spacing:.07em;text-transform:uppercase">View</span>
      <button id="tHi">Highlight</button><button id="tAl">Align to block</button>
      <span id="ordnote" style="color:var(--ink-3);font-size:12.5px"></span>
    </div>
    <div class="nav" id="nav" hidden>
      <button id="prev">&larr;</button><span class="mono" id="exlabel"></span><button id="next">&rarr;</button>
      <span id="exnote" style="color:var(--ink-2)"></span>
    </div>
    <div class="panel" style="margin-top:18px"><h2>Per color</h2>
      <table><thead><tr><th>Color</th><th>Avoids</th><th style="text-align:right">Edges</th>
      <th style="text-align:right">Max common nbrs</th><th style="text-align:right">Limit</th></tr></thead>
      <tbody id="stats"><tr><td colspan="5" style="color:var(--ink-3)">&mdash;</td></tr></tbody></table>
    </div>
  </div>
</div>
<div class="note">
<strong>What is being checked.</strong> A monochromatic K<sub>s,t</sub> in color <em>c</em> is
<em>s</em> vertices against <em>t</em> other vertices with every one of the <em>s&middot;t</em> edges
between them in color <em>c</em>. Nothing is required of the edges inside either set. A clique
K<sub>k</sub> is <em>k</em> vertices with all internal edges one color.
<p><strong>The two view toggles.</strong> On the grid a clique is a square straddling the
diagonal, because the same vertices index rows and columns. A complete bipartite subgraph is an
off-diagonal rectangle instead &mdash; but only when its rows and columns happen to be adjacent, and
the tightest sets usually carry scattered labels. <em>Align to block</em> permutes the axes to gather
them, so the rectangle becomes contiguous and gets outlined; relabeling vertices never changes an
edge's color, so it is the same object seen from a better angle. Keep the original order to read
global structure instead &mdash; a circulant's diagonal banding exists only in that numbering and
disappears under any reordering. <em>Highlight</em> is independent of both: turn it off to see the
raw coloring at full contrast.
<p>Bipartite cases are decided by counting common neighborhoods, which is equivalent to enumerating
placements and far cheaper; cliques are enumerated directly. Stepping through the highlights walks the
tightest configurations &mdash; the sets that come closest to forcing the forbidden graph without
doing so.
</div>
</div>
"""
TAIL = r"""
<script>
const $=id=>document.getElementById(id);
let ST=null, exIdx=0, hlOn=true, alOn=false, ORD=null;

function parseSpec(s){
  return s.split(",").map(t=>t.trim()).filter(Boolean).map(t=>{
    let m=/^K(\d+)x(\d+)$/i.exec(t); if(m) return {kind:"bip",s:+m[1],t:+m[2],label:`K_{${m[1]},${m[2]}}`};
    m=/^B(\d+)$/i.exec(t); if(m) return {kind:"book",t:+m[1],label:`B_${m[1]}`};
    m=/^K(\d+)$/i.exec(t); if(m) return {kind:"clique",k:+m[1],label:`K_${m[1]}`};
    throw new Error(`don't recognise "${t}" — use K3x5, B5 or K4`);
  });
}
function parseWitness(txt){
  const col=new Map(); let n=0; const seen=new Set();
  txt.split(/\n/).forEach((ln,idx)=>{
    ln=ln.trim(); if(!ln||ln.startsWith("#")) return;
    const p=ln.split(/\s+/).map(Number);
    if(p.length!==3||p.some(isNaN)) throw new Error(`line ${idx+1}: expected "i j c"`);
    let [i,j,c]=p; if(i===j) throw new Error(`line ${idx+1}: self loop at ${i}`);
    if(i>j)[i,j]=[j,i];
    const k=i*10000+j;
    if(seen.has(k)) throw new Error(`edge ${i},${j} appears twice`);
    seen.add(k); col.set(k,c); n=Math.max(n,j);
  });
  const need=n*(n-1)/2;
  if(col.size!==need) throw new Error(`got ${col.size} edges; a complete K_${n} needs ${need}`);
  return {n,col};
}
const C=(S,i,j)=>S.col.get(Math.min(i,j)*10000+Math.max(i,j));
function common(S,A,c){const out=[];
  for(let w=1;w<=S.n;w++){ if(A.includes(w))continue;
    let ok=true; for(const a of A) if(C(S,a,w)!==c){ok=false;break;}
    if(ok) out.push(w);} return out;}
function combos(n,k,fn){const idx=[...Array(k).keys()].map(x=>x+1);
  for(;;){ if(fn(idx.slice())) return true;
    let p=k-1; while(p>=0&&idx[p]===n-k+p+1)p--; if(p<0)return false;
    idx[p]++; for(let q=p+1;q<k;q++) idx[q]=idx[q-1]+1; }}
function analyse(S,spec){
  return spec.map((g,gi)=>{
    const c=gi+1; let edges=0;
    for(let i=1;i<=S.n;i++)for(let j=i+1;j<=S.n;j++) if(C(S,i,j)===c) edges++;
    if(g.kind==="book"){
      // B_t sits on an EDGE of colour c, unlike K_{s,t} which sits on any pair.
      let best=-1,bestA=null,viol=null,tight=0;
      for(let u=1;u<=S.n;u++)for(let v=u+1;v<=S.n;v++){
        if(C(S,u,v)!==c) continue;
        const cn=common(S,[u,v],c);
        if(cn.length>best){best=cn.length;bestA=[u,v];}
        if(cn.length>=g.t&&!viol) viol={A:[u,v],B:cn.slice(0,g.t)};
      }
      if(!viol) for(let u=1;u<=S.n;u++)for(let v=u+1;v<=S.n;v++)
        if(C(S,u,v)===c&&common(S,[u,v],c).length===best) tight++;
      const A=viol?viol.A:(bestA||[1,2]), B=viol?viol.B:common(S,A,c);
      return {c,g,edges,max:viol?viol.B.length:best,limit:g.t-1,viol,
              hi:{A,B},tight,setSize:2};
    }
    if(g.kind==="bip"){
      let best=-1,bestA=null,viol=null,tight=0;
      combos(S.n,g.s,A=>{const cn=common(S,A,c);
        if(cn.length>best){best=cn.length;bestA=A;}
        if(cn.length>=g.t){viol={A,B:cn.slice(0,g.t)};return true;} return false;});
      if(!viol) combos(S.n,g.s,A=>{ if(common(S,A,c).length===best) tight++; return false;});
      const A=viol?viol.A:bestA, B=viol?viol.B:common(S,A,c);
      return {c,g,edges,max:viol?viol.B.length:best,limit:g.t-1,viol,
              hi:{A,B},tight,setSize:g.s};
    }
    let viol=null;
    combos(S.n,g.k,A=>{ for(let a=0;a<A.length;a++)for(let b=a+1;b<A.length;b++)
        if(C(S,A[a],A[b])!==c) return false; viol={A,B:A}; return true;});
    return {c,g,edges,max:null,limit:null,viol,hi:viol?{A:viol.A,B:viol.A}:null,tight:0,setSize:g.k};
  });
}
function order(n,cur){
  // Aligning permutes the axes so the s-set and its common neighborhood sit adjacent: a
  // combinatorial rectangle is only a VISIBLE rectangle when its rows and columns happen
  // to be contiguous, which for scattered vertex labels they are not. Relabeling never
  // changes an edge's color, so it is the same object. The original order is the one that
  // shows global structure - a circulant's diagonal banding exists only in that numbering.
  if(!alOn||!cur) return [...Array(n).keys()].map(k=>k+1);
  const A=cur.hi.A, B=cur.hi.B, used=new Set([...A,...B]);
  return [...A,...B,...[...Array(n).keys()].map(k=>k+1).filter(v=>!used.has(v))];
}
function render(){
  const cv=$("cv"),x=cv.getContext("2d");
  const css=getComputedStyle(document.documentElement);
  const tok=k=>css.getPropertyValue(k).trim();
  x.clearRect(0,0,cv.width,cv.height);
  if(!ST){x.fillStyle=tok("--ink-3");x.font="14px "+tok("--sans");
    x.fillText("No coloring loaded.",22,34);return;}
  const {S,res}=ST, n=S.n, pad=n>26?16:26, s=(cv.width-pad)/n;
  const hiRes=res.filter(r=>r.hi);
  const cur=hiRes.length?hiRes[exIdx%hiRes.length]:null;   // stepped config, independent of the toggles
  const A=new Set(cur&&hlOn?cur.hi.A:[]), B=new Set(cur&&hlOn?cur.hi.B:[]);
  const hot=cur&&cur.c===1?tok("--e1-hot"):tok("--e2-hot");
  const ord=order(n,cur);
  for(let a=0;a<n;a++)for(let b=0;b<n;b++){
    const i=ord[a], j=ord[b]; let f;
    if(i===j) f=tok("--rule-2");
    else{ const v=C(S,i,j);
      const on=hlOn&&cur&&((A.has(i)&&B.has(j))||(B.has(i)&&A.has(j)));
      const dim=hlOn&&cur;
      f = on ? hot : (v===1?(dim?tok("--e1-dim"):tok("--e1")):(dim?tok("--e2-dim"):tok("--e2")));}
    x.fillStyle=f; x.fillRect(pad+b*s,pad+a*s,Math.max(1,s-0.7),Math.max(1,s-0.7));
  }
  if(alOn&&cur){ // outline the two blocks that make the rectangle explicit
    const na=cur.hi.A.length, nb=cur.hi.B.length;
    x.strokeStyle=hot; x.lineWidth=1.6;
    x.strokeRect(pad+na*s-0.8,pad-0.8,nb*s,na*s);
    x.strokeRect(pad-0.8,pad+na*s-0.8,na*s,nb*s);
  }
  if(pad>16){x.font="10px "+tok("--mono");
    for(let k=0;k<n;k++){const lab=ord[k], on=hlOn&&(A.has(lab)||B.has(lab));
      x.fillStyle=on?hot:tok("--ink-3");
      x.fillText(String(lab),pad+k*s+s/2-(lab>9?6:3),15);
      x.fillText(String(lab),1,pad+k*s+s/2+4);}}
  ORD=ord;
}
function show(){
  const {S,res}=ST;
  const bad=res.filter(r=>r.viol);
  const v=$("verdict"), vt=$("vtext");
  v.className="verdict "+(bad.length?"bad":"ok");
  vt.innerHTML = bad.length
    ? `Contains ${bad.map(r=>`a ${r.g.label} in color ${r.c}`).join(" and ")}. Not a valid witness.`
    : `No forbidden subgraph found on K<sub>${S.n}</sub>. If the input is right, R &gt; ${S.n}.`;
  $("stats").innerHTML = res.map(r=>`<tr><td>${r.c}</td><td>${r.g.label}</td>
    <td class="num">${r.edges}</td>
    <td class="num">${r.max===null?"&mdash;":r.max}</td>
    <td class="num">${r.limit===null?"&mdash;":r.limit}</td></tr>`).join("");
  $("tHi").className = hlOn?"primary":"";
  $("tAl").className = alOn?"primary":"";
  $("ordnote").textContent = alOn ? "axes reordered" : "original vertex order";
  const hi=res.filter(r=>r.hi);
  $("nav").hidden = !hi.length;
  if(hi.length){
    const cur=hi[exIdx%hi.length];
    $("exlabel").textContent=`{${cur.hi.A.join(",")}} × {${cur.hi.B.join(",")}}`;
    $("exnote").innerHTML = cur.viol
      ? `all ${cur.hi.A.length*cur.hi.B.length} edges color ${cur.c} — this is a ${cur.g.label}`
      : (cur.g.kind==="bip"
         ? `${cur.hi.A.length}×${cur.hi.B.length} in color ${cur.c}; ${cur.g.label} needs ${cur.g.t} columns, so one short${cur.tight?` (${cur.tight} such sets tie here)`:""}`
         : `no ${cur.g.label} in color ${cur.c}`);
  }
  render();
}
function run(){
  $("err").textContent="";
  try{
    const spec=parseSpec($("spec").value);
    const S=parseWitness($("wit").value);
    if(spec.length<1) throw new Error("name at least one forbidden graph");
    ST={S,res:analyse(S,spec)}; exIdx=0; show();
  }catch(e){ $("err").textContent=e.message;
    $("verdict").className="verdict idle"; $("vtext").textContent="Could not read that input."; }
}
$("run").onclick=run;
$("clear").onclick=()=>{$("wit").value="";$("err").textContent="";ST=null;
  $("verdict").className="verdict idle";$("vtext").textContent="Nothing checked yet.";
  $("stats").innerHTML='<tr><td colspan="5" style="color:var(--ink-3)">&mdash;</td></tr>';
  $("nav").hidden=true; render();};
$("tHi").onclick=()=>{hlOn=!hlOn;show();};
$("tAl").onclick=()=>{alOn=!alOn;show();};
$("next").onclick=()=>{exIdx++;show();};
$("prev").onclick=()=>{const h=ST.res.filter(r=>r.hi).length;exIdx=(exIdx+h-1)%h;show();};
$("cv").onmousemove=e=>{ if(!ST)return;
  const r=$("cv").getBoundingClientRect(),sc=$("cv").width/r.width;
  const n=ST.S.n,pad=n>26?16:26,s=($("cv").width-pad)/n;
  const b=Math.floor(((e.clientX-r.left)*sc-pad)/s), a=Math.floor(((e.clientY-r.top)*sc-pad)/s);
  const ord=ORD||[...Array(n).keys()].map(k=>k+1);
  if(a<0||b<0||a>=n||b>=n){$("hover").textContent="";return;}
  const i=ord[a], j=ord[b];
  $("hover").textContent = i!==j ? `edge ${i}–${j} is color ${C(ST.S,i,j)}` : "";};
$("cv").onmouseleave=()=>$("hover").textContent="";
$("chips").innerHTML=Object.entries(EXAMPLES).map(([k,v])=>
  `<button class="chip" data-k="${k}">${v.name}</button>`).join("");
$("chips").onclick=e=>{const k=e.target.dataset.k; if(!k)return;
  $("spec").value=EXAMPLES[k].spec; $("wit").value=EXAMPLES[k].data; run();};
const BOOT=Object.keys(EXAMPLES)[0];   // keys are the witness "# name:" lines, so
$("spec").value=EXAMPLES[BOOT].spec;   // never hard-code one: adding a witness renames them
$("wit").value=EXAMPLES[BOOT].data; run();
matchMedia("(prefers-color-scheme:dark)").addEventListener("change",render);
</script>
"""

if __name__ == "__main__":
    main()
