/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_fam.py. Do not edit.
   `famH k v8 v9 v10`: the `wordEdges` lists of the listed words of family (k, v8, v9, v10), and
   `famH_spec`: it is `(listedWords (certOf …)).map (wordEdges k)` for every key of `famKeys`. -/
import RootedM5.Fam.W_k10_c0100
import RootedM5.Fam.W_k10_c019
import RootedM5.Fam.W_k10_c028
import RootedM5.Fam.W_k10_c037
import RootedM5.Fam.W_k10_c046
import RootedM5.Fam.W_k10_c055
import RootedM5.Fam.W_k10_c064
import RootedM5.Fam.W_k10_c073
import RootedM5.Fam.W_k10_c082
import RootedM5.Fam.W_k10_c091
import RootedM5.Fam.W_k8_c008
import RootedM5.Fam.W_k8_c017
import RootedM5.Fam.W_k8_c026
import RootedM5.Fam.W_k8_c035
import RootedM5.Fam.W_k8_c044
import RootedM5.Fam.W_k8_c053
import RootedM5.Fam.W_k8_c062
import RootedM5.Fam.W_k8_c071
import RootedM5.Fam.W_k8_c080
import RootedM5.Fam.W_k8_c107
import RootedM5.Fam.W_k8_c116
import RootedM5.Fam.W_k8_c125
import RootedM5.Fam.W_k8_c134
import RootedM5.Fam.W_k8_c143
import RootedM5.Fam.W_k8_c152
import RootedM5.Fam.W_k8_c161
import RootedM5.Fam.W_k8_c170
import RootedM5.Fam.W_k8_c206
import RootedM5.Fam.W_k8_c215
import RootedM5.Fam.W_k8_c224
import RootedM5.Fam.W_k8_c233
import RootedM5.Fam.W_k8_c242
import RootedM5.Fam.W_k8_c251
import RootedM5.Fam.W_k8_c260
import RootedM5.Fam.W_k8_c305
import RootedM5.Fam.W_k8_c314
import RootedM5.Fam.W_k8_c323
import RootedM5.Fam.W_k8_c332
import RootedM5.Fam.W_k8_c341
import RootedM5.Fam.W_k8_c350
import RootedM5.Fam.W_k8_c404
import RootedM5.Fam.W_k8_c413
import RootedM5.Fam.W_k8_c422
import RootedM5.Fam.W_k8_c431
import RootedM5.Fam.W_k8_c440
import RootedM5.Fam.W_k8_c503
import RootedM5.Fam.W_k8_c512
import RootedM5.Fam.W_k8_c521
import RootedM5.Fam.W_k8_c530
import RootedM5.Fam.W_k8_c602
import RootedM5.Fam.W_k8_c611
import RootedM5.Fam.W_k8_c620
import RootedM5.Fam.W_k9_c090
import RootedM4.CoverData.All

namespace SB.Rooted.M5
open SB.Rooted.M4 SB.Rooted.M4.Cover SB.Rooted.M4.CoverData SB.Rooted.M5.Fam

def famLWs : List ((Nat × Nat × Nat × Nat) × List (List (Nat × Nat))) := [((10, 0, 10, 0), LW_k10_c0100), ((10, 0, 1, 9), LW_k10_c019), ((10, 0, 2, 8), LW_k10_c028), ((10, 0, 3, 7), LW_k10_c037), ((10, 0, 4, 6), LW_k10_c046), ((10, 0, 5, 5), LW_k10_c055), ((10, 0, 6, 4), LW_k10_c064), ((10, 0, 7, 3), LW_k10_c073), ((10, 0, 8, 2), LW_k10_c082), ((10, 0, 9, 1), LW_k10_c091), ((8, 0, 0, 8), LW_k8_c008), ((8, 0, 1, 7), LW_k8_c017), ((8, 0, 2, 6), LW_k8_c026), ((8, 0, 3, 5), LW_k8_c035), ((8, 0, 4, 4), LW_k8_c044), ((8, 0, 5, 3), LW_k8_c053), ((8, 0, 6, 2), LW_k8_c062), ((8, 0, 7, 1), LW_k8_c071), ((8, 0, 8, 0), LW_k8_c080), ((8, 1, 0, 7), LW_k8_c107), ((8, 1, 1, 6), LW_k8_c116), ((8, 1, 2, 5), LW_k8_c125), ((8, 1, 3, 4), LW_k8_c134), ((8, 1, 4, 3), LW_k8_c143), ((8, 1, 5, 2), LW_k8_c152), ((8, 1, 6, 1), LW_k8_c161), ((8, 1, 7, 0), LW_k8_c170), ((8, 2, 0, 6), LW_k8_c206), ((8, 2, 1, 5), LW_k8_c215), ((8, 2, 2, 4), LW_k8_c224), ((8, 2, 3, 3), LW_k8_c233), ((8, 2, 4, 2), LW_k8_c242), ((8, 2, 5, 1), LW_k8_c251), ((8, 2, 6, 0), LW_k8_c260), ((8, 3, 0, 5), LW_k8_c305), ((8, 3, 1, 4), LW_k8_c314), ((8, 3, 2, 3), LW_k8_c323), ((8, 3, 3, 2), LW_k8_c332), ((8, 3, 4, 1), LW_k8_c341), ((8, 3, 5, 0), LW_k8_c350), ((8, 4, 0, 4), LW_k8_c404), ((8, 4, 1, 3), LW_k8_c413), ((8, 4, 2, 2), LW_k8_c422), ((8, 4, 3, 1), LW_k8_c431), ((8, 4, 4, 0), LW_k8_c440), ((8, 5, 0, 3), LW_k8_c503), ((8, 5, 1, 2), LW_k8_c512), ((8, 5, 2, 1), LW_k8_c521), ((8, 5, 3, 0), LW_k8_c530), ((8, 6, 0, 2), LW_k8_c602), ((8, 6, 1, 1), LW_k8_c611), ((8, 6, 2, 0), LW_k8_c620), ((9, 0, 9, 0), LW_k9_c090)]

def famH (k v8 v9 v10 : Nat) : List (List (Nat × Nat)) :=
  ((famLWs.find? (fun p => p.1 == (k, v8, v9, v10))).map (·.2)).getD []

theorem famH_k10_c0100 : (listedWords (certOf 10 0 10 0)).map (wordEdges 10) = famH 10 0 10 0 := by
  rw [show certOf 10 0 10 0 = k10_c0100 from rfl, show famH 10 0 10 0 = LW_k10_c0100 from rfl]
  exact famLW_k10_c0100
theorem famH_k10_c019 : (listedWords (certOf 10 0 1 9)).map (wordEdges 10) = famH 10 0 1 9 := by
  rw [show certOf 10 0 1 9 = k10_c019 from rfl, show famH 10 0 1 9 = LW_k10_c019 from rfl]
  exact famLW_k10_c019
theorem famH_k10_c028 : (listedWords (certOf 10 0 2 8)).map (wordEdges 10) = famH 10 0 2 8 := by
  rw [show certOf 10 0 2 8 = k10_c028 from rfl, show famH 10 0 2 8 = LW_k10_c028 from rfl]
  exact famLW_k10_c028
theorem famH_k10_c037 : (listedWords (certOf 10 0 3 7)).map (wordEdges 10) = famH 10 0 3 7 := by
  rw [show certOf 10 0 3 7 = k10_c037 from rfl, show famH 10 0 3 7 = LW_k10_c037 from rfl]
  exact famLW_k10_c037
theorem famH_k10_c046 : (listedWords (certOf 10 0 4 6)).map (wordEdges 10) = famH 10 0 4 6 := by
  rw [show certOf 10 0 4 6 = k10_c046 from rfl, show famH 10 0 4 6 = LW_k10_c046 from rfl]
  exact famLW_k10_c046
theorem famH_k10_c055 : (listedWords (certOf 10 0 5 5)).map (wordEdges 10) = famH 10 0 5 5 := by
  rw [show certOf 10 0 5 5 = k10_c055 from rfl, show famH 10 0 5 5 = LW_k10_c055 from rfl]
  exact famLW_k10_c055
theorem famH_k10_c064 : (listedWords (certOf 10 0 6 4)).map (wordEdges 10) = famH 10 0 6 4 := by
  rw [show certOf 10 0 6 4 = k10_c064 from rfl, show famH 10 0 6 4 = LW_k10_c064 from rfl]
  exact famLW_k10_c064
theorem famH_k10_c073 : (listedWords (certOf 10 0 7 3)).map (wordEdges 10) = famH 10 0 7 3 := by
  rw [show certOf 10 0 7 3 = k10_c073 from rfl, show famH 10 0 7 3 = LW_k10_c073 from rfl]
  exact famLW_k10_c073
theorem famH_k10_c082 : (listedWords (certOf 10 0 8 2)).map (wordEdges 10) = famH 10 0 8 2 := by
  rw [show certOf 10 0 8 2 = k10_c082 from rfl, show famH 10 0 8 2 = LW_k10_c082 from rfl]
  exact famLW_k10_c082
theorem famH_k10_c091 : (listedWords (certOf 10 0 9 1)).map (wordEdges 10) = famH 10 0 9 1 := by
  rw [show certOf 10 0 9 1 = k10_c091 from rfl, show famH 10 0 9 1 = LW_k10_c091 from rfl]
  exact famLW_k10_c091
theorem famH_k8_c008 : (listedWords (certOf 8 0 0 8)).map (wordEdges 8) = famH 8 0 0 8 := by
  rw [show certOf 8 0 0 8 = k8_c008 from rfl, show famH 8 0 0 8 = LW_k8_c008 from rfl]
  exact famLW_k8_c008
theorem famH_k8_c017 : (listedWords (certOf 8 0 1 7)).map (wordEdges 8) = famH 8 0 1 7 := by
  rw [show certOf 8 0 1 7 = k8_c017 from rfl, show famH 8 0 1 7 = LW_k8_c017 from rfl]
  exact famLW_k8_c017
theorem famH_k8_c026 : (listedWords (certOf 8 0 2 6)).map (wordEdges 8) = famH 8 0 2 6 := by
  rw [show certOf 8 0 2 6 = k8_c026 from rfl, show famH 8 0 2 6 = LW_k8_c026 from rfl]
  exact famLW_k8_c026
theorem famH_k8_c035 : (listedWords (certOf 8 0 3 5)).map (wordEdges 8) = famH 8 0 3 5 := by
  rw [show certOf 8 0 3 5 = k8_c035 from rfl, show famH 8 0 3 5 = LW_k8_c035 from rfl]
  exact famLW_k8_c035
theorem famH_k8_c044 : (listedWords (certOf 8 0 4 4)).map (wordEdges 8) = famH 8 0 4 4 := by
  rw [show certOf 8 0 4 4 = k8_c044 from rfl, show famH 8 0 4 4 = LW_k8_c044 from rfl]
  exact famLW_k8_c044
theorem famH_k8_c053 : (listedWords (certOf 8 0 5 3)).map (wordEdges 8) = famH 8 0 5 3 := by
  rw [show certOf 8 0 5 3 = k8_c053 from rfl, show famH 8 0 5 3 = LW_k8_c053 from rfl]
  exact famLW_k8_c053
theorem famH_k8_c062 : (listedWords (certOf 8 0 6 2)).map (wordEdges 8) = famH 8 0 6 2 := by
  rw [show certOf 8 0 6 2 = k8_c062 from rfl, show famH 8 0 6 2 = LW_k8_c062 from rfl]
  exact famLW_k8_c062
theorem famH_k8_c071 : (listedWords (certOf 8 0 7 1)).map (wordEdges 8) = famH 8 0 7 1 := by
  rw [show certOf 8 0 7 1 = k8_c071 from rfl, show famH 8 0 7 1 = LW_k8_c071 from rfl]
  exact famLW_k8_c071
theorem famH_k8_c080 : (listedWords (certOf 8 0 8 0)).map (wordEdges 8) = famH 8 0 8 0 := by
  rw [show certOf 8 0 8 0 = k8_c080 from rfl, show famH 8 0 8 0 = LW_k8_c080 from rfl]
  exact famLW_k8_c080
theorem famH_k8_c107 : (listedWords (certOf 8 1 0 7)).map (wordEdges 8) = famH 8 1 0 7 := by
  rw [show certOf 8 1 0 7 = k8_c107 from rfl, show famH 8 1 0 7 = LW_k8_c107 from rfl]
  exact famLW_k8_c107
theorem famH_k8_c116 : (listedWords (certOf 8 1 1 6)).map (wordEdges 8) = famH 8 1 1 6 := by
  rw [show certOf 8 1 1 6 = k8_c116 from rfl, show famH 8 1 1 6 = LW_k8_c116 from rfl]
  exact famLW_k8_c116
theorem famH_k8_c125 : (listedWords (certOf 8 1 2 5)).map (wordEdges 8) = famH 8 1 2 5 := by
  rw [show certOf 8 1 2 5 = k8_c125 from rfl, show famH 8 1 2 5 = LW_k8_c125 from rfl]
  exact famLW_k8_c125
theorem famH_k8_c134 : (listedWords (certOf 8 1 3 4)).map (wordEdges 8) = famH 8 1 3 4 := by
  rw [show certOf 8 1 3 4 = k8_c134 from rfl, show famH 8 1 3 4 = LW_k8_c134 from rfl]
  exact famLW_k8_c134
theorem famH_k8_c143 : (listedWords (certOf 8 1 4 3)).map (wordEdges 8) = famH 8 1 4 3 := by
  rw [show certOf 8 1 4 3 = k8_c143 from rfl, show famH 8 1 4 3 = LW_k8_c143 from rfl]
  exact famLW_k8_c143
theorem famH_k8_c152 : (listedWords (certOf 8 1 5 2)).map (wordEdges 8) = famH 8 1 5 2 := by
  rw [show certOf 8 1 5 2 = k8_c152 from rfl, show famH 8 1 5 2 = LW_k8_c152 from rfl]
  exact famLW_k8_c152
theorem famH_k8_c161 : (listedWords (certOf 8 1 6 1)).map (wordEdges 8) = famH 8 1 6 1 := by
  rw [show certOf 8 1 6 1 = k8_c161 from rfl, show famH 8 1 6 1 = LW_k8_c161 from rfl]
  exact famLW_k8_c161
theorem famH_k8_c170 : (listedWords (certOf 8 1 7 0)).map (wordEdges 8) = famH 8 1 7 0 := by
  rw [show certOf 8 1 7 0 = k8_c170 from rfl, show famH 8 1 7 0 = LW_k8_c170 from rfl]
  exact famLW_k8_c170
theorem famH_k8_c206 : (listedWords (certOf 8 2 0 6)).map (wordEdges 8) = famH 8 2 0 6 := by
  rw [show certOf 8 2 0 6 = k8_c206 from rfl, show famH 8 2 0 6 = LW_k8_c206 from rfl]
  exact famLW_k8_c206
theorem famH_k8_c215 : (listedWords (certOf 8 2 1 5)).map (wordEdges 8) = famH 8 2 1 5 := by
  rw [show certOf 8 2 1 5 = k8_c215 from rfl, show famH 8 2 1 5 = LW_k8_c215 from rfl]
  exact famLW_k8_c215
theorem famH_k8_c224 : (listedWords (certOf 8 2 2 4)).map (wordEdges 8) = famH 8 2 2 4 := by
  rw [show certOf 8 2 2 4 = k8_c224 from rfl, show famH 8 2 2 4 = LW_k8_c224 from rfl]
  exact famLW_k8_c224
theorem famH_k8_c233 : (listedWords (certOf 8 2 3 3)).map (wordEdges 8) = famH 8 2 3 3 := by
  rw [show certOf 8 2 3 3 = k8_c233 from rfl, show famH 8 2 3 3 = LW_k8_c233 from rfl]
  exact famLW_k8_c233
theorem famH_k8_c242 : (listedWords (certOf 8 2 4 2)).map (wordEdges 8) = famH 8 2 4 2 := by
  rw [show certOf 8 2 4 2 = k8_c242 from rfl, show famH 8 2 4 2 = LW_k8_c242 from rfl]
  exact famLW_k8_c242
theorem famH_k8_c251 : (listedWords (certOf 8 2 5 1)).map (wordEdges 8) = famH 8 2 5 1 := by
  rw [show certOf 8 2 5 1 = k8_c251 from rfl, show famH 8 2 5 1 = LW_k8_c251 from rfl]
  exact famLW_k8_c251
theorem famH_k8_c260 : (listedWords (certOf 8 2 6 0)).map (wordEdges 8) = famH 8 2 6 0 := by
  rw [show certOf 8 2 6 0 = k8_c260 from rfl, show famH 8 2 6 0 = LW_k8_c260 from rfl]
  exact famLW_k8_c260
theorem famH_k8_c305 : (listedWords (certOf 8 3 0 5)).map (wordEdges 8) = famH 8 3 0 5 := by
  rw [show certOf 8 3 0 5 = k8_c305 from rfl, show famH 8 3 0 5 = LW_k8_c305 from rfl]
  exact famLW_k8_c305
theorem famH_k8_c314 : (listedWords (certOf 8 3 1 4)).map (wordEdges 8) = famH 8 3 1 4 := by
  rw [show certOf 8 3 1 4 = k8_c314 from rfl, show famH 8 3 1 4 = LW_k8_c314 from rfl]
  exact famLW_k8_c314
theorem famH_k8_c323 : (listedWords (certOf 8 3 2 3)).map (wordEdges 8) = famH 8 3 2 3 := by
  rw [show certOf 8 3 2 3 = k8_c323 from rfl, show famH 8 3 2 3 = LW_k8_c323 from rfl]
  exact famLW_k8_c323
theorem famH_k8_c332 : (listedWords (certOf 8 3 3 2)).map (wordEdges 8) = famH 8 3 3 2 := by
  rw [show certOf 8 3 3 2 = k8_c332 from rfl, show famH 8 3 3 2 = LW_k8_c332 from rfl]
  exact famLW_k8_c332
theorem famH_k8_c341 : (listedWords (certOf 8 3 4 1)).map (wordEdges 8) = famH 8 3 4 1 := by
  rw [show certOf 8 3 4 1 = k8_c341 from rfl, show famH 8 3 4 1 = LW_k8_c341 from rfl]
  exact famLW_k8_c341
theorem famH_k8_c350 : (listedWords (certOf 8 3 5 0)).map (wordEdges 8) = famH 8 3 5 0 := by
  rw [show certOf 8 3 5 0 = k8_c350 from rfl, show famH 8 3 5 0 = LW_k8_c350 from rfl]
  exact famLW_k8_c350
theorem famH_k8_c404 : (listedWords (certOf 8 4 0 4)).map (wordEdges 8) = famH 8 4 0 4 := by
  rw [show certOf 8 4 0 4 = k8_c404 from rfl, show famH 8 4 0 4 = LW_k8_c404 from rfl]
  exact famLW_k8_c404
theorem famH_k8_c413 : (listedWords (certOf 8 4 1 3)).map (wordEdges 8) = famH 8 4 1 3 := by
  rw [show certOf 8 4 1 3 = k8_c413 from rfl, show famH 8 4 1 3 = LW_k8_c413 from rfl]
  exact famLW_k8_c413
theorem famH_k8_c422 : (listedWords (certOf 8 4 2 2)).map (wordEdges 8) = famH 8 4 2 2 := by
  rw [show certOf 8 4 2 2 = k8_c422 from rfl, show famH 8 4 2 2 = LW_k8_c422 from rfl]
  exact famLW_k8_c422
theorem famH_k8_c431 : (listedWords (certOf 8 4 3 1)).map (wordEdges 8) = famH 8 4 3 1 := by
  rw [show certOf 8 4 3 1 = k8_c431 from rfl, show famH 8 4 3 1 = LW_k8_c431 from rfl]
  exact famLW_k8_c431
theorem famH_k8_c440 : (listedWords (certOf 8 4 4 0)).map (wordEdges 8) = famH 8 4 4 0 := by
  rw [show certOf 8 4 4 0 = k8_c440 from rfl, show famH 8 4 4 0 = LW_k8_c440 from rfl]
  exact famLW_k8_c440
theorem famH_k8_c503 : (listedWords (certOf 8 5 0 3)).map (wordEdges 8) = famH 8 5 0 3 := by
  rw [show certOf 8 5 0 3 = k8_c503 from rfl, show famH 8 5 0 3 = LW_k8_c503 from rfl]
  exact famLW_k8_c503
theorem famH_k8_c512 : (listedWords (certOf 8 5 1 2)).map (wordEdges 8) = famH 8 5 1 2 := by
  rw [show certOf 8 5 1 2 = k8_c512 from rfl, show famH 8 5 1 2 = LW_k8_c512 from rfl]
  exact famLW_k8_c512
theorem famH_k8_c521 : (listedWords (certOf 8 5 2 1)).map (wordEdges 8) = famH 8 5 2 1 := by
  rw [show certOf 8 5 2 1 = k8_c521 from rfl, show famH 8 5 2 1 = LW_k8_c521 from rfl]
  exact famLW_k8_c521
theorem famH_k8_c530 : (listedWords (certOf 8 5 3 0)).map (wordEdges 8) = famH 8 5 3 0 := by
  rw [show certOf 8 5 3 0 = k8_c530 from rfl, show famH 8 5 3 0 = LW_k8_c530 from rfl]
  exact famLW_k8_c530
theorem famH_k8_c602 : (listedWords (certOf 8 6 0 2)).map (wordEdges 8) = famH 8 6 0 2 := by
  rw [show certOf 8 6 0 2 = k8_c602 from rfl, show famH 8 6 0 2 = LW_k8_c602 from rfl]
  exact famLW_k8_c602
theorem famH_k8_c611 : (listedWords (certOf 8 6 1 1)).map (wordEdges 8) = famH 8 6 1 1 := by
  rw [show certOf 8 6 1 1 = k8_c611 from rfl, show famH 8 6 1 1 = LW_k8_c611 from rfl]
  exact famLW_k8_c611
theorem famH_k8_c620 : (listedWords (certOf 8 6 2 0)).map (wordEdges 8) = famH 8 6 2 0 := by
  rw [show certOf 8 6 2 0 = k8_c620 from rfl, show famH 8 6 2 0 = LW_k8_c620 from rfl]
  exact famLW_k8_c620
theorem famH_k9_c090 : (listedWords (certOf 9 0 9 0)).map (wordEdges 9) = famH 9 0 9 0 := by
  rw [show certOf 9 0 9 0 = k9_c090 from rfl, show famH 9 0 9 0 = LW_k9_c090 from rfl]
  exact famLW_k9_c090

theorem famH_spec : ∀ key ∈ famKeys,
    (listedWords (certOf key.1 key.2.1 key.2.2.1 key.2.2.2)).map (wordEdges key.1) =
      famH key.1 key.2.1 key.2.2.1 key.2.2.2 := by
  intro key hk
  simp only [famKeys, List.mem_cons, List.not_mem_nil, or_false] at hk
  rcases hk with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  exacts [famH_k10_c0100, famH_k10_c019, famH_k10_c028, famH_k10_c037, famH_k10_c046, famH_k10_c055, famH_k10_c064, famH_k10_c073, famH_k10_c082, famH_k10_c091, famH_k8_c008, famH_k8_c017, famH_k8_c026, famH_k8_c035, famH_k8_c044, famH_k8_c053, famH_k8_c062, famH_k8_c071, famH_k8_c080, famH_k8_c107, famH_k8_c116, famH_k8_c125, famH_k8_c134, famH_k8_c143, famH_k8_c152, famH_k8_c161, famH_k8_c170, famH_k8_c206, famH_k8_c215, famH_k8_c224, famH_k8_c233, famH_k8_c242, famH_k8_c251, famH_k8_c260, famH_k8_c305, famH_k8_c314, famH_k8_c323, famH_k8_c332, famH_k8_c341, famH_k8_c350, famH_k8_c404, famH_k8_c413, famH_k8_c422, famH_k8_c431, famH_k8_c440, famH_k8_c503, famH_k8_c512, famH_k8_c521, famH_k8_c530, famH_k8_c602, famH_k8_c611, famH_k8_c620, famH_k9_c090]

end SB.Rooted.M5

#print axioms SB.Rooted.M5.famH_spec
