/- Generated by ramsey/runs/k28_rooted/m5_final/m5_gen_lean.py. Do not edit. -/
import RootedM5.Data.D00
import RootedM5.Data.D01
import RootedM5.Data.D02
import RootedM5.Data.D03
import RootedM5.Data.D04
import RootedM5.Data.D05
import RootedM5.Data.D06
import RootedM5.Data.D07
import RootedM5.Data.D08
import RootedM5.Data.D09

namespace SB.Rooted.M5
open SB.Rooted.M5.Data

/-- The 781 census cases with their cubes (sorted list tags). -/
def table : List CaseRows := cases00 ++ cases01 ++ cases02 ++ cases03 ++ cases04 ++ cases05 ++ cases06 ++ cases07 ++ cases08 ++ cases09

/-- The 23,886 cubes. -/
def rows : List Row := table.flatMap CaseRows.rows

end SB.Rooted.M5
